/* =============================================================
   FORMICARIUM :: DEEP COLONY
   geometry.js - procedural mesh construction (no external assets)
   Every model in this game is generated by code at load time.
   ============================================================= */
(function (AF) {
  'use strict';

  var M = AF.M, v3 = M.v3;
  var G = {};

  // ------------------------------------------------------------------
  //  MeshBuilder: accumulates pos / nrm / uv / part, with a transform
  //  stack. part = vec4(partId, segT, side, jitter)
  // ------------------------------------------------------------------
  function Builder() {
    this.pos = []; this.nrm = []; this.uv = []; this.part = []; this.idx = [];
    this.tx = 0; this.ty = 0; this.tz = 0;
    this.sx = 1; this.sy = 1; this.sz = 1;
    this.rot = null;             // 3x3 row-major flat
    this.p0 = 0; this.p1 = 0; this.p2 = 0; this.p3 = 0;
  }
  Builder.prototype.setPart = function (a, b, c, d) {
    this.p0 = a || 0; this.p1 = b || 0; this.p2 = c || 0; this.p3 = d || 0; return this;
  };
  Builder.prototype.reset = function () {
    this.tx = this.ty = this.tz = 0; this.sx = this.sy = this.sz = 1; this.rot = null; return this;
  };
  Builder.prototype.at = function (x, y, z) { this.tx = x; this.ty = y; this.tz = z; return this; };
  Builder.prototype.scl = function (x, y, z) { this.sx = x; this.sy = y === undefined ? x : y; this.sz = z === undefined ? x : z; return this; };
  Builder.prototype.rotFromAxis = function (dir, upHint) {
    // builds a basis with Z along dir
    var z = v3.normalize(v3.create(), dir);
    var up = upHint || [0, 1, 0];
    if (Math.abs(v3.dot(z, up)) > 0.98) up = [1, 0, 0];
    var x = v3.normalize(v3.create(), v3.cross(v3.create(), up, z));
    var y = v3.cross(v3.create(), z, x);
    this.rot = [x[0], y[0], z[0], x[1], y[1], z[1], x[2], y[2], z[2]];
    return this;
  };
  Builder.prototype.rotEuler = function (rx, ry, rz) {
    var cx = Math.cos(rx), sx = Math.sin(rx), cy = Math.cos(ry), sy = Math.sin(ry), cz = Math.cos(rz), sz = Math.sin(rz);
    // R = Ry * Rx * Rz
    var m = [
      cy * cz + sy * sx * sz, -cy * sz + sy * sx * cz, sy * cx,
      cx * sz, cx * cz, -sx,
      -sy * cz + cy * sx * sz, sy * sz + cy * sx * cz, cy * cx
    ];
    this.rot = m;
    return this;
  };
  Builder.prototype.vert = function (px, py, pz, nx, ny, nz, u, v) {
    var x = px * this.sx, y = py * this.sy, z = pz * this.sz;
    var mx = nx / this.sx, my = ny / this.sy, mz = nz / this.sz;
    if (this.rot) {
      var r = this.rot;
      var X = r[0] * x + r[1] * y + r[2] * z;
      var Y = r[3] * x + r[4] * y + r[5] * z;
      var Z = r[6] * x + r[7] * y + r[8] * z;
      x = X; y = Y; z = Z;
      X = r[0] * mx + r[1] * my + r[2] * mz;
      Y = r[3] * mx + r[4] * my + r[5] * mz;
      Z = r[6] * mx + r[7] * my + r[8] * mz;
      mx = X; my = Y; mz = Z;
    }
    var l = Math.sqrt(mx * mx + my * my + mz * mz) || 1;
    this.pos.push(x + this.tx, y + this.ty, z + this.tz);
    this.nrm.push(mx / l, my / l, mz / l);
    this.uv.push(u || 0, v || 0);
    this.part.push(this.p0, this.p1, this.p2, this.p3);
    return this.pos.length / 3 - 1;
  };
  Builder.prototype.tri = function (a, b, c) { this.idx.push(a, b, c); };
  Builder.prototype.quad = function (a, b, c, d) { this.idx.push(a, b, c, a, c, d); };
  Builder.prototype.vertCount = function () { return this.pos.length / 3; };

  // --- primitives -------------------------------------------------
  Builder.prototype.ellipsoid = function (segU, segV, squash) {
    var base = this.vertCount(), i, j;
    squash = squash || 0;
    for (j = 0; j <= segV; j++) {
      var v = j / segV, phi = v * Math.PI;
      var sp = Math.sin(phi), cp = Math.cos(phi);
      for (i = 0; i <= segU; i++) {
        var u = i / segU, th = u * M.TAU;
        var x = sp * Math.cos(th), y = cp, z = sp * Math.sin(th);
        var yy = y - squash * (1 - Math.abs(y)) * 0.0;
        this.vert(x, yy, z, x, y, z, u, v);
      }
    }
    for (j = 0; j < segV; j++) {
      for (i = 0; i < segU; i++) {
        var a = base + j * (segU + 1) + i, b = a + segU + 1;
        this.quad(a, a + 1, b + 1, b);
      }
    }
    return this;
  };
  // tapered capsule from origin along +Z, length L, radii r0..r1
  Builder.prototype.limb = function (L, r0, r1, seg, rings, tBase, tSpan) {
    var base = this.vertCount(), i, j;
    rings = rings || 3;
    tBase = tBase || 0; tSpan = tSpan === undefined ? 1 : tSpan;
    for (j = 0; j <= rings; j++) {
      var t = j / rings;
      var z = t * L;
      var r = M.lerp(r0, r1, t);
      var savedP1 = this.p1;
      this.p1 = tBase + t * tSpan;
      for (i = 0; i <= seg; i++) {
        var th = i / seg * M.TAU;
        var cx = Math.cos(th), cy = Math.sin(th);
        this.vert(cx * r, cy * r, z, cx, cy, (r0 - r1) / L * 0.6, i / seg, t);
      }
      this.p1 = savedP1;
    }
    for (j = 0; j < rings; j++) {
      for (i = 0; i < seg; i++) {
        var a = base + j * (seg + 1) + i, b = a + seg + 1;
        this.quad(a, b, b + 1, a + 1);
      }
    }
    // caps
    var savedP = this.p1;
    this.p1 = tBase;
    var c0 = this.vert(0, 0, -r0 * 0.6, 0, 0, -1, 0.5, 0);
    for (i = 0; i < seg; i++) this.tri(c0, base + i + 1, base + i);
    this.p1 = tBase + tSpan;
    var top = base + rings * (seg + 1);
    var c1 = this.vert(0, 0, L + r1 * 0.6, 0, 0, 1, 0.5, 1);
    for (i = 0; i < seg; i++) this.tri(c1, top + i, top + i + 1);
    this.p1 = savedP;
    return this;
  };
  Builder.prototype.boxFaces = function (hx, hy, hz, inside) {
    var b = this;
    var n = inside ? -1 : 1;
    var faces = [
      [[1, 0, 0], [0, 1, 0], [0, 0, 1]], [[-1, 0, 0], [0, 1, 0], [0, 0, -1]],
      [[0, 1, 0], [0, 0, 1], [1, 0, 0]], [[0, -1, 0], [0, 0, -1], [1, 0, 0]],
      [[0, 0, 1], [0, 1, 0], [-1, 0, 0]], [[0, 0, -1], [0, 1, 0], [1, 0, 0]]
    ];
    for (var f = 0; f < faces.length; f++) {
      var nz = faces[f][0], uu = faces[f][1], vv = faces[f][2];
      var base = b.vertCount();
      for (var k = 0; k < 4; k++) {
        var su = (k === 1 || k === 2) ? 1 : -1;
        var sv = (k >= 2) ? 1 : -1;
        var px = (nz[0] + uu[0] * su + vv[0] * sv) * hx;
        var py = (nz[1] + uu[1] * su + vv[1] * sv) * hy;
        var pz = (nz[2] + uu[2] * su + vv[2] * sv) * hz;
        b.vert(px, py, pz, nz[0] * n, nz[1] * n, nz[2] * n, (su + 1) * 0.5, (sv + 1) * 0.5);
      }
      if (inside) b.quad(base, base + 3, base + 2, base + 1);
      else b.quad(base, base + 1, base + 2, base + 3);
    }
    return this;
  };
  Builder.prototype.disc = function (r, seg, ny) {
    var base = this.vertCount();
    var c = this.vert(0, 0, 0, 0, ny, 0, 0.5, 0.5);
    for (var i = 0; i <= seg; i++) {
      var th = i / seg * M.TAU;
      this.vert(Math.cos(th) * r, 0, Math.sin(th) * r, 0, ny, 0, Math.cos(th) * 0.5 + 0.5, Math.sin(th) * 0.5 + 0.5);
    }
    for (i = 0; i < seg; i++) {
      if (ny > 0) this.tri(c, base + i + 2, base + i + 1);
      else this.tri(c, base + i + 1, base + i + 2);
    }
    return this;
  };

  Builder.prototype.build = function (program, extraAttribs) {
    var attribs = [
      { name: 'aPos', size: 3, data: new Float32Array(this.pos) },
      { name: 'aNrm', size: 3, data: new Float32Array(this.nrm) },
      { name: 'aUV', size: 2, data: new Float32Array(this.uv) },
      { name: 'aPart', size: 4, data: new Float32Array(this.part) }
    ];
    if (extraAttribs) for (var i = 0; i < extraAttribs.length; i++) attribs.push(extraAttribs[i]);
    var idx = this.pos.length / 3 > 65535 ? new Uint32Array(this.idx) : new Uint16Array(this.idx);
    var mesh = new AF.GLX.Mesh(attribs, idx, program);
    mesh.triCount = this.idx.length / 3;
    return mesh;
  };
  G.Builder = Builder;

  // ------------------------------------------------------------------
  //  PART IDS (must match shaders.js ANT_VS)
  // ------------------------------------------------------------------
  G.PART = {
    THORAX: 0, HEAD: 1, GASTER: 2,
    LEG0: 3, LEG1: 4, LEG2: 5, LEG3: 6, LEG4: 7, LEG5: 8,
    ANTENNA: 9, MANDIBLE: 10, PETIOLE: 11, WING: 12, CARGO: 13
  };
  // leg attach points, must match shader constant array
  G.LEG_ATTACH = [
    [0.085, 0.15, 0.155], [0.095, 0.145, 0.045], [0.09, 0.14, -0.06],
    [-0.085, 0.15, 0.155], [-0.095, 0.145, 0.045], [-0.09, 0.14, -0.06]
  ];

  // ------------------------------------------------------------------
  //  THE ANT
  //  Local space: +Z forward, +Y up, feet at y=0, body core at y~0.17
  //  lod: 0 = hero, 1 = mid, 2 = far blob
  // ------------------------------------------------------------------
  G.buildAnt = function (lod, opts) {
    opts = opts || {};
    var b = new Builder();
    var P = G.PART;
    var su = lod === 0 ? 14 : (lod === 1 ? 8 : 5);
    var sv = lod === 0 ? 10 : (lod === 1 ? 6 : 4);
    var bodyY = 0.17;
    var headScale = opts.head || 1.0;
    var gasterScale = opts.gaster || 1.0;
    var legLen = opts.legLen || 1.0;

    // ---- gaster (abdomen) ----
    //  THREE overlapping masses, not one ellipsoid with rings around it.
    //
    //  The old build was a single smooth gaster wearing three bands that
    //  stood 2% proud of its surface. A 2% bump is not a normal break, so
    //  the Sobel ink pass in the post chain found nothing, and at ordinary
    //  play distance the ant read as one smooth orange lozenge - a blob
    //  with legs - while every other animal in the tank read as an insect.
    //
    //  Masses that genuinely cross produce a crease the ink pass DRAWS. It
    //  is the same trick as the beetle's elytra seam, the woodlouse's
    //  tergites and the spider's abdomen. Centres are spaced 0.110 against
    //  a mean z-radius of 0.088 - deep enough never to gap, shallow enough
    //  that the crossing stays angular. The steps are TRANSVERSE, so they
    //  break the outline from the side and from above, where a lengthwise
    //  stripe would run edge-on and contribute nothing.
    //
    //  Built at every lod on purpose: the distance where the ant most needs
    //  help is exactly the distance where it used to lose its rings.
    var GSEG = [
      { z: -0.175, w: 0.115, h: 0.116, d: 0.085 },
      { z: -0.285, w: 0.137, h: 0.135, d: 0.098 },
      { z: -0.395, w: 0.105, h: 0.101, d: 0.082 }
    ];
    for (var gi = 0; gi < 3; gi++) {
      var G3 = GSEG[gi];
      b.reset().setPart(P.GASTER, 0, 0, 0);
      //  Grow BACKWARD from the waist, do not scale the position outright.
      //  A queen's gasterScale is 2.35; multiplying z by it walks the whole
      //  abdomen rearward and tears it off the petiole, leaving a gap. This
      //  anchors the front of the first segment at z = -0.09, exactly where
      //  the petiole ends, at every caste scale.
      b.at(0, bodyY + 0.012, -0.06 + (G3.z + 0.06) * gasterScale)
        .scl(G3.w * gasterScale, G3.h * gasterScale, G3.d * gasterScale);
      b.ellipsoid(su, sv);
    }

    // ---- petiole (waist nodes) ----
    b.reset().setPart(P.PETIOLE, 0, 0, 0);
    b.at(0, bodyY + 0.02, -0.145).scl(0.036, 0.05, 0.045);
    b.ellipsoid(Math.max(5, su - 4), Math.max(4, sv - 3));
    b.reset().setPart(P.PETIOLE, 0, 0, 0);
    b.at(0, bodyY + 0.005, -0.09).scl(0.03, 0.038, 0.035);
    b.ellipsoid(Math.max(5, su - 4), Math.max(4, sv - 3));

    // ---- alitrunk (thorax) ----
    b.reset().setPart(P.THORAX, 0, 0, 0);
    b.at(0, bodyY + 0.015, 0.03).scl(0.098, 0.10, 0.155);
    b.ellipsoid(su, sv);
    if (lod === 0) {
      // pronotum hump
      b.reset().setPart(P.THORAX, 0, 0, 0);
      b.at(0, bodyY + 0.055, 0.075).scl(0.072, 0.055, 0.075);
      b.ellipsoid(su, sv);
      // propodeal spines
      for (var s = -1; s <= 1; s += 2) {
        b.reset().setPart(P.THORAX, 0, 0, 0);
        b.at(s * 0.045, bodyY + 0.055, -0.055).rotFromAxis([s * 0.4, 0.6, -0.7]);
        b.limb(0.075, 0.016, 0.002, 5, 1, 0, 0);
      }
    }

    // ---- head ----
    b.reset().setPart(P.HEAD, 0, 0, 0);
    b.at(0, bodyY + 0.022, 0.272).scl(0.112 * headScale, 0.100 * headScale, 0.118 * headScale);
    b.ellipsoid(su, sv);
    // eyes
    if (lod <= 1) {
      for (var e = -1; e <= 1; e += 2) {
        b.reset().setPart(P.HEAD, 0, 0, 1);
        b.at(e * 0.078 * headScale, bodyY + 0.045, 0.285).scl(0.032, 0.038, 0.028);
        b.ellipsoid(Math.max(6, su - 4), Math.max(5, sv - 3));
      }
    }
    // mandibles
    for (var mi = -1; mi <= 1; mi += 2) {
      b.reset().setPart(P.MANDIBLE, 0, mi, 0);
      b.at(mi * 0.045 * headScale, bodyY + 0.0, 0.335 * headScale)
        .rotFromAxis([mi * 0.42, -0.08, 0.9]);
      b.limb(0.115 * headScale, 0.021 * headScale, 0.004, lod === 0 ? 7 : 5, lod === 0 ? 3 : 1, 0, 1);
      if (lod === 0) {
        // mandible tooth
        b.reset().setPart(P.MANDIBLE, 0.6, mi, 0);
        b.at(mi * 0.078 * headScale, bodyY - 0.008, 0.40 * headScale).rotFromAxis([mi * 0.2, -0.4, 0.6]);
        b.limb(0.032, 0.010, 0.001, 4, 1, 0.6, 0.2);
      }
    }
    // antennae : scape + funiculus
    for (var ai = -1; ai <= 1; ai += 2) {
      b.reset().setPart(P.ANTENNA, 0, ai, 0);
      b.at(ai * 0.04, bodyY + 0.055, 0.315).rotFromAxis([ai * 0.55, 0.42, 0.72]);
      b.limb(0.16, 0.012, 0.008, lod === 0 ? 6 : 4, lod === 0 ? 3 : 1, 0.0, 0.45);
      b.reset().setPart(P.ANTENNA, 0.5, ai, 0);
      b.at(ai * 0.128, bodyY + 0.122, 0.43).rotFromAxis([ai * 0.30, -0.25, 0.92]);
      b.limb(0.135, 0.0085, 0.005, lod === 0 ? 6 : 4, lod === 0 ? 3 : 1, 0.5, 0.5);
    }

    // ---- legs ----
    //  Rounder and thinner. At 6 sides a leg this narrow silhouettes as a
    //  flat ribbon; 9 reads as a cylinder, and the extra ring lets the knee
    //  actually bend instead of kinking.
    var legSeg = lod === 0 ? 9 : 5;
    var legRing = lod === 0 ? 3 : 1;
    for (var L = 0; L < 6; L++) {
      var A = G.LEG_ATTACH[L];
      var side = L < 3 ? 1 : -1;
      var fwd = [0.16, 0.0, -0.16][L % 3];
      var pid = P.LEG0 + L;
      // femur : out & up
      var kneeX = A[0] + side * 0.20 * legLen;
      var kneeY = A[1] + 0.115 * legLen;
      var kneeZ = A[2] + fwd * 0.55;
      b.reset().setPart(pid, 0, side, 0);
      b.at(A[0], A[1], A[2]).rotFromAxis([kneeX - A[0], kneeY - A[1], kneeZ - A[2]]);
      var fl = Math.sqrt(Math.pow(kneeX - A[0], 2) + Math.pow(kneeY - A[1], 2) + Math.pow(kneeZ - A[2], 2));
      b.limb(fl, 0.0150, 0.0098, legSeg, legRing, 0.0, 0.45);
      // tibia : down & out to foot
      var footX = kneeX + side * 0.115 * legLen;
      var footY = 0.006;
      var footZ = kneeZ + fwd * 0.85;
      b.reset().setPart(pid, 0.45, side, 0);
      b.at(kneeX, kneeY, kneeZ).rotFromAxis([footX - kneeX, footY - kneeY, footZ - kneeZ]);
      var tl = Math.sqrt(Math.pow(footX - kneeX, 2) + Math.pow(footY - kneeY, 2) + Math.pow(footZ - kneeZ, 2));
      b.limb(tl, 0.0098, 0.0034, legSeg, legRing, 0.45, 0.55);
    }
    return b;
  };

  // winged reproductive: ant + wings
  G.buildAlate = function (lod) {
    var b = G.buildAnt(lod, { gaster: 1.25, head: 1.05 });
    var P = G.PART;
    for (var s = -1; s <= 1; s += 2) {
      for (var w = 0; w < 2; w++) {
        var len = w === 0 ? 0.62 : 0.44;
        var wid = w === 0 ? 0.15 : 0.11;
        var base = b.vertCount();
        b.reset().setPart(P.WING, w, s, 0);
        b.at(s * 0.03, 0.255, 0.02 - w * 0.06).rotEuler(0, s * (0.30 + w * 0.18), 0);
        var segs = lod === 0 ? 10 : 5;
        for (var i = 0; i <= segs; i++) {
          var t = i / segs;
          var wz = -t * len;
          var ww = Math.sin(t * Math.PI * 0.92) * wid * (1 - t * 0.35);
          b.setPart(P.WING, t, s, w);
          b.vert(s * ww * 0.15, 0.004, wz, 0, 1, 0, t, 0);
          b.vert(s * ww, 0.0, wz - ww * 0.15, 0, 1, 0, t, 1);
        }
        for (i = 0; i < segs; i++) {
          var a = base + i * 2;
          b.quad(a, a + 2, a + 3, a + 1);
          b.quad(a, a + 1, a + 3, a + 2);
        }
      }
    }
    return b;
  };

  // queen: massive gaster, big thorax
  G.buildQueen = function (lod) {
    return G.buildAnt(lod, { gaster: 2.35, head: 1.35, legLen: 1.15 });
  };
  G.buildSoldier = function (lod) {
    return G.buildAnt(lod, { gaster: 1.15, head: 1.75, legLen: 1.1 });
  };

  // ------------------------------------------------------------------
  //  BROOD : egg / larva / pupa
  // ------------------------------------------------------------------
  G.buildBrood = function () {
    var b = new Builder();
    // stage encoded in aPart.x : 0 egg, 1 larva, 2 pupa - we build all 3 in one
    // mesh but use aPart.w as a "visible for stage" selector in the shader.
    b.reset().setPart(0, 0, 0, 0).at(0, 0.05, 0).scl(0.05, 0.062, 0.05);
    b.ellipsoid(9, 7);
    b.reset().setPart(0, 0, 0, 1).at(0, 0.06, 0).scl(0.055, 0.06, 0.10);
    b.ellipsoid(10, 8);
    b.reset().setPart(0, 0, 0, 1).at(0, 0.068, 0.07).scl(0.038, 0.04, 0.045);
    b.ellipsoid(8, 6);
    b.reset().setPart(0, 0, 0, 2).at(0, 0.062, 0).scl(0.06, 0.065, 0.115);
    b.ellipsoid(10, 8);
    return b;
  };

  // ------------------------------------------------------------------
  //  PROPS
  // ------------------------------------------------------------------
  G.buildPebble = function (seed, detail) {
    var rng = new M.RNG(seed);
    var b = new Builder();
    var su = detail || 10, sv = Math.max(6, (detail || 10) - 2);
    var base = b.vertCount();
    var warp = [];
    for (var j = 0; j <= sv; j++) {
      for (var i = 0; i <= su; i++) {
        var u = i / su, v = j / sv;
        var th = u * M.TAU, phi = v * Math.PI;
        var x = Math.sin(phi) * Math.cos(th), y = Math.cos(phi), z = Math.sin(phi) * Math.sin(th);
        var r = 1 + 0.30 * (M.fbm3(x * 2.1 + seed, y * 2.1, z * 2.1, 3) - 0.5) + 0.14 * (M.fbm3(x * 5 + seed, y * 5, z * 5, 2) - 0.5);
        if (i === su) r = warp[j];
        else if (i === 0) warp[j] = r;
        b.vert(x * r, y * r * 0.78, z * r, x, y * 1.2, z, u, v);
      }
    }
    for (j = 0; j < sv; j++) for (i = 0; i < su; i++) {
      var a = base + j * (su + 1) + i, bb = a + su + 1;
      b.quad(a, a + 1, bb + 1, bb);
    }
    return b;
  };

  //  A real blade of grass: a keeled (V-folded) strip that tapers, bends and
  //  twists. The fold is what makes it read as grass instead of a flat card -
  //  each wing catches the light at a different angle all the way up.
  G.buildGrassBlade = function (seed) {
    var rng = new M.RNG(seed || 7);
    var b = new Builder();
    var segs = 11;
    var h = rng.range(1.0, 2.4);
    var bendX = rng.range(0.14, 0.62) * rng.sign();
    var bendZ = rng.range(-0.30, 0.30);
    var twist = rng.range(-0.75, 0.75);
    var keel = rng.range(0.40, 0.85);
    var base = b.vertCount();
    for (var i = 0; i <= segs; i++) {
      var t = i / segs;
      // width: swells slightly above the sheath, then tapers to a point
      var w = 0.075 * (1 - Math.pow(t, 1.7) * 0.97) * (0.62 + 0.42 * Math.sin(t * 2.3 + 0.35));
      var y = t * h;
      var x = bendX * t * t * h * 0.55;
      var z = bendZ * t * t * h * 0.40;
      var tw = twist * t * t;
      var ax = Math.cos(tw), az = Math.sin(tw);
      var kh = w * keel;
      b.setPart(0, t, 0, 0);
      b.vert(x - ax * w, y - kh * 0.15, z - az * w, -ax * 0.62, 0.78, -az * 0.62, 0.0, t);
      b.vert(x, y + kh, z, 0, 1, 0, 0.5, t);
      b.vert(x + ax * w, y - kh * 0.15, z + az * w, ax * 0.62, 0.78, az * 0.62, 1.0, t);
    }
    for (i = 0; i < segs; i++) {
      var a = base + i * 3;
      b.quad(a, a + 3, a + 4, a + 1);
      b.quad(a + 1, a + 4, a + 5, a + 2);
    }
    return b;
  };

  //  Fallen leaf: cupped across the midrib and curled along it, so it never
  //  looks like a flat triangle fan lying on the dirt.
  G.buildLeaf = function (seed) {
    var rng = new M.RNG((seed || 0) + 91);
    var b = new Builder();
    var segs = 13, across = 5;
    var len = rng.range(1.25, 1.75);
    var cup = rng.range(0.16, 0.34);          // curl across the blade
    var curl = rng.range(0.10, 0.30);         // lift of the tip
    var lean = rng.range(-0.18, 0.18);
    var base = b.vertCount();
    for (var i = 0; i <= segs; i++) {
      var t = i / segs;
      // ovate silhouette, widest a third of the way along
      var w = Math.pow(Math.sin(Math.pow(t, 0.78) * Math.PI), 0.85) * 0.44;
      var z = -t * len;
      var spine = curl * t * t * len - Math.sin(t * 2.1) * 0.045;
      for (var j = 0; j <= across; j++) {
        var u = j / across;
        var s = u * 2 - 1;                    // -1 .. 1 across the leaf
        var x = s * w + lean * t * t;
        // cup: edges rise away from the midrib
        var y = spine + cup * s * s * w * 1.6 + (1 - Math.abs(s)) * 0.03;
        var nx = -s * cup * 2.4, nz = -(curl * 2.0 * t);
        b.setPart(0, t, s, 1);
        b.vert(x, y, z, nx, 1.0, nz, u, t);
      }
    }
    var stride = across + 1;
    for (i = 0; i < segs; i++) {
      for (j = 0; j < across; j++) {
        var a = base + i * stride + j;
        b.quad(a, a + stride, a + stride + 1, a + 1);
      }
    }
    // petiole
    b.reset().setPart(0, 0, 0, 1).at(0, 0.01, 0.02).rotFromAxis([0, 0.12, 1]);
    b.limb(0.22, 0.022, 0.012, 5, 1, 0, 0.1);
    return b;
  };

  G.buildTwig = function (seed) {
    var rng = new M.RNG(seed || 3);
    var b = new Builder();
    b.reset().setPart(0, 0, 0, 0).rotFromAxis([0.2, 0.06, 1]);
    b.limb(2.4, 0.075, 0.045, 7, 4, 0, 1);
    for (var i = 0; i < 3; i++) {
      var t = 0.35 + i * 0.22;
      b.reset().setPart(0, 0, 0, 0).at(0.2 * t * 2.4, 0.06 * t * 2.4, t * 2.4)
        .rotFromAxis([rng.range(-1, 1), rng.range(0.2, 0.9), rng.range(0.4, 1)]);
      b.limb(rng.range(0.4, 0.9), 0.035, 0.012, 5, 2, 0, 1);
    }
    return b;
  };

  G.buildMushroom = function (seed) {
    var rng = new M.RNG((seed || 0) + 5);
    var b = new Builder();
    var stemH = rng.range(0.42, 0.70);
    var capR = rng.range(0.22, 0.32);
    // stem
    b.reset().setPart(0, 0, 0, 2).rotEuler(-Math.PI / 2, 0, 0);
    b.limb(stemH, 0.048, 0.070, 10, 3, 0, 0.55);
    //  CLEAR THE STEM'S ROTATION BEFORE THE CAP.
    //
    //  limb() runs along +z, so the stem needs rotEuler(-PI/2) to stand up.
    //  The cap below is authored directly in world axes - its y already has
    //  stemH added in - so it must be built with no rotation at all. Leaving
    //  the stem's rotation set fed the cap through (x,y,z) -> (x, z, -y) and
    //  laid it flat on the sand behind the stem, a vertical disc reading as a
    //  dartboard in the dirt: bbox y -0.226..0.462, z -0.584..0.067, with the
    //  cap's whole extent in z where it belonged in y.
    b.reset();
    // cap: a domed skirt with a rolled rim, built as a lathe so the
    // underside is a real surface the light can catch
    var segU = 18, segV = 8;
    var base = b.vertCount();
    for (var j = 0; j <= segV; j++) {
      var v = j / segV;
      // profile from apex (v=0) out to the rim and slightly under
      var prof = Math.sin(v * Math.PI * 0.62);
      var r = capR * prof * (1 + 0.10 * Math.sin(v * 7.0));
      var y = stemH + capR * 0.72 * Math.cos(v * Math.PI * 0.62) - capR * 0.12 * v * v;
      for (var i = 0; i <= segU; i++) {
        var u = i / segU, th = u * M.TAU;
        var ripple = 1 + 0.055 * Math.sin(th * 7.0 + rng.s * 0.0);
        b.setPart(0, v, 0, 2);
        b.vert(Math.cos(th) * r * ripple, y, Math.sin(th) * r * ripple,
          Math.cos(th) * prof, Math.max(0.25, Math.cos(v * 1.9)), Math.sin(th) * prof, u, v);
      }
    }
    for (j = 0; j < segV; j++) for (i = 0; i < segU; i++) {
      var a = base + j * (segU + 1) + i, bb = a + segU + 1;
      b.quad(a, a + 1, bb + 1, bb);
    }
    //  Skirt: close the cap by folding the rim back down and inward. This
    //  gives a real shaded underside instead of a flat disc floating at the
    //  cap's waist (which read as a dartboard lying on the ground).
    var rimY = stemH + capR * 0.72 * Math.cos(Math.PI * 0.62) - capR * 0.12;
    var rimR = capR * Math.sin(Math.PI * 0.62);
    var under = 5;
    var ub = b.vertCount();
    for (var w = 0; w <= under; w++) {
      var tv = w / under;
      var rr = rimR * (1 - tv) + capR * 0.10 * tv;
      var yy = rimY + tv * capR * 0.30;
      for (i = 0; i <= segU; i++) {
        var th2 = i / segU * M.TAU;
        b.setPart(0, 1, 0, 3);
        b.vert(Math.cos(th2) * rr, yy, Math.sin(th2) * rr,
          Math.cos(th2) * 0.25, -1, Math.sin(th2) * 0.25, i / segU, tv);
      }
    }
    for (w = 0; w < under; w++) for (i = 0; i < segU; i++) {
      var ua = ub + w * (segU + 1) + i, ubb = ua + segU + 1;
      b.quad(ua, ubb, ubb + 1, ua + 1);
    }
    return b;
  };

  G.buildCrystal = function (seed) {
    // sugar crystal: irregular prism
    var rng = new M.RNG(seed || 11);
    var b = new Builder();
    var sides = 6;
    var base = b.vertCount();
    var rr = [];
    for (var i = 0; i < sides; i++) rr.push(rng.range(0.6, 1.15));
    for (var k = 0; k < 2; k++) {
      var y = k ? 0.62 : 0.0;
      var sc = k ? 0.72 : 1.0;
      for (i = 0; i <= sides; i++) {
        var th = (i % sides) / sides * M.TAU + 0.3;
        var r = rr[i % sides] * sc * 0.34;
        b.vert(Math.cos(th) * r, y, Math.sin(th) * r, Math.cos(th), 0.1, Math.sin(th), i / sides, k);
      }
    }
    for (i = 0; i < sides; i++) {
      var a = base + i, bb = a + sides + 1;
      b.quad(a, bb, bb + 1, a + 1);
    }
    var tip = b.vert(0, 0.95, 0, 0, 1, 0, 0.5, 1);
    var bot = b.vert(0, -0.16, 0, 0, -1, 0, 0.5, 0);
    for (i = 0; i < sides; i++) {
      b.tri(tip, base + sides + 1 + i, base + sides + 2 + i);
      b.tri(bot, base + i + 1, base + i);
    }
    return b;
  };

  G.buildSeed = function () {
    var b = new Builder();
    b.reset().setPart(0, 0, 0, 0).scl(0.22, 0.17, 0.30).at(0, 0.17, 0);
    b.ellipsoid(11, 8);
    return b;
  };

  //  A puddle, not a bead. Water that has settled on soil spreads into a
  //  shallow lens with a slightly domed middle and a thin feathered edge -
  //  drawing it as the falling-droplet mesh made pools look like glass marbles
  //  sitting on the dirt.
  G.buildPuddle = function () {
    var b = new Builder();
    var rings = 7, segs = 24;
    var base = b.vertCount();
    for (var j = 0; j <= rings; j++) {
      var v = j / rings;
      var r = v;
      // domed centre falling to a very thin rim
      var h = Math.cos(v * Math.PI * 0.5);
      h = h * h * 0.17;
      for (var i = 0; i <= segs; i++) {
        var th = i / segs * M.TAU;
        // a slightly irregular outline so it never reads as a perfect circle
        var wob = 1 + 0.06 * Math.sin(th * 3.0) + 0.035 * Math.sin(th * 7.0 + 1.3);
        var nx = Math.cos(th) * v * 0.55, nz = Math.sin(th) * v * 0.55;
        b.setPart(0, v, 0, 0);
        b.vert(Math.cos(th) * r * wob, h, Math.sin(th) * r * wob,
          nx, 1.0, nz, i / segs, v);
      }
    }
    for (j = 0; j < rings; j++) for (i = 0; i < segs; i++) {
      var a = base + j * (segs + 1) + i, bb = a + segs + 1;
      b.quad(a, a + 1, bb + 1, bb);
    }
    return b;
  };

  G.buildDroplet = function () {
    var b = new Builder();
    var su = 16, sv = 12, base = b.vertCount();
    for (var j = 0; j <= sv; j++) {
      var v = j / sv, phi = v * Math.PI;
      var sp = Math.sin(phi), cp = Math.cos(phi);
      var squash = 1.0 - 0.42 * M.smoothstep(0.4, 1.0, v);
      for (var i = 0; i <= su; i++) {
        var u = i / su, th = u * M.TAU;
        b.vert(sp * Math.cos(th) * (1 + (1 - squash) * 0.5), cp * squash * 0.86 + 0.14, sp * Math.sin(th) * (1 + (1 - squash) * 0.5),
          sp * Math.cos(th), cp, sp * Math.sin(th), u, v);
      }
    }
    for (j = 0; j < sv; j++) for (i = 0; i < su; i++) {
      var a = base + j * (su + 1) + i, bb = a + su + 1;
      b.quad(a, a + 1, bb + 1, bb);
    }
    return b;
  };

  // dead insect / aphid : protein food
  G.buildAphid = function () {
    var b = new Builder();
    b.reset().setPart(0, 0, 0, 0).at(0, 0.16, -0.05).scl(0.22, 0.185, 0.28);
    b.ellipsoid(12, 9);
    b.reset().setPart(0, 0, 0, 0).at(0, 0.15, 0.24).scl(0.11, 0.10, 0.10);
    b.ellipsoid(9, 7);
    for (var s = -1; s <= 1; s += 2) {
      for (var l = 0; l < 3; l++) {
        b.reset().setPart(0, 0, 0, 0).at(s * 0.14, 0.13, 0.12 - l * 0.13).rotFromAxis([s * 0.9, -0.9, 0.1]);
        b.limb(0.20, 0.015, 0.006, 4, 1, 0, 1);
      }
    }
    return b;
  };

  // ------------------------------------------------------------------
  //  PREDATOR : wolf spider
  // ------------------------------------------------------------------
  G.buildSpider = function () {
    var b = new Builder();
    var P = G.PART;
    var s, L, i;

  //  RIGID LIMB PART ID.
  //
  //  A limb needs two things that used to be in conflict. The fragment
  //  shader gives limbs their dark matte material - and sets limb=1.0 to
  //  kill the fresnel rim - on the test pid > 2.5 && pid < 10.5. The vertex
  //  shader's animPart rotates 3..8 (legs), 9 (antenna) and 10 (mandible)
  //  about attach points hard-coded for an ANT, which mangles anything
  //  bigger. Parking limbs on part 0 avoided the mangling but lost the
  //  material, and the legs came out pale against a dark body - exactly the
  //  "read as white paper" failure the shader's own comment warns about.
  //
  //  2.75 sits in the gap between the two: it passes the material test and
  //  matches NO animation branch. Dark matte limbs, no fresnel rim, no
  //  rotation about somebody else's hip.
  var LIMB = 2.75;


    //  a limb between two points, so the tables below read as anatomy
    var bone = function (side, p0, p1, r0, r1, nseg, rings, t0, t1) {
      var ax = side * p0[0], ay = p0[1], az = p0[2];
      var bx = side * p1[0], by = p1[1], bz = p1[2];
      var dx = bx - ax, dy = by - ay, dz = bz - az;
      b.reset().setPart(LIMB, 0, side, 0).at(ax, ay, az).rotFromAxis([dx, dy, dz]);
      b.limb(Math.sqrt(dx * dx + dy * dy + dz * dz), r0, r1, nseg, rings, t0, t1);
    };

    // --- CEPHALOTHORAX ------------------------------------------------
    //  Wide and LOW, and deliberately wider than the abdomen (0.375 against
    //  0.305). The old build was 0.34 against a 0.42 abdomen, which put the
    //  animal's widest point at its tail and made it read as an egg with a
    //  bump in front. A hunting spider's mass is at the shoulders, where the
    //  legs come out.
    b.reset().setPart(P.THORAX, 0, 0, 0).at(0, 0.400, 0.130).scl(0.375, 0.205, 0.365);
    b.ellipsoid(16, 11);

    //  Ocular tubercle: the raised head region, standing 0.056 proud of the
    //  carapace hull, so their intersection is a crease AND the eyes get a
    //  face to sit on instead of a flat forehead. It is on P.HEAD, not
    //  P.THORAX, on purpose: animPart has no branch for pid 1, so the
    //  tubercle and the eyes pinned to it are both perfectly still. On the
    //  carapace it would bob 0.004 under stationary eyes and the small ones
    //  would submerge and re-emerge once per step.
    b.reset().setPart(P.HEAD, 0, 0, 0).at(0, 0.478, 0.350).scl(0.210, 0.150, 0.235);
    b.ellipsoid(13, 9);

    // --- THE PEDICEL --------------------------------------------------
    //  The waist is the whole difference between a spider and a beetle, and
    //  the old mesh had none: the two ellipsoids interpenetrated over 0.21
    //  of z and the outline swelled monotonically from face to tail. Here
    //  the narrowest cross-section is 0.082 half-width at z = -0.315,
    //  against a 0.375 shoulder - a 22% pinch, tighter than the ant's own
    //  petiole. It is pinched in Y too (0.088 against 0.245), so the waist
    //  shows from any yaw and not just from above. DO NOT WIDEN IT.
    b.reset().setPart(P.THORAX, 0, 0, 0).at(0, 0.400, -0.262).scl(0.095, 0.088, 0.105);
    b.ellipsoid(9, 7);

    // --- ABDOMEN ------------------------------------------------------
    //  Three overlapping masses, not one egg. Centres are spaced ~1.04x
    //  their z-radius, the same band the woodlouse tergites and the cricket
    //  abdomen use: deep enough not to gap, shallow enough that the crossing
    //  stays angular and inks. The steps are TRANSVERSE on purpose - at a
    //  five-degree camera a transverse step breaks the top outline, where a
    //  longitudinal stripe would run edge-on and contribute nothing.
    //
    //  Stays on P.GASTER for the +/-0.008 bob. With every limb now rigid it
    //  is the only motion left on the animal, and the pedicel is buried
    //  0.057 into the front segment, far more than the 0.012 of shear.
    b.reset().setPart(P.GASTER, 0, 0, 0).at(0, 0.408, -0.505).scl(0.285, 0.245, 0.195);
    b.ellipsoid(14, 10);
    b.reset().setPart(P.GASTER, 0, 0, 0).at(0, 0.398, -0.710).scl(0.305, 0.258, 0.200);
    b.ellipsoid(14, 10);
    b.reset().setPart(P.GASTER, 0, 0, 0).at(0, 0.352, -0.905).scl(0.208, 0.175, 0.180);
    b.ellipsoid(10, 7);

    // --- EYES ---------------------------------------------------------
    //  The rule that fixes this: each bead's CENTRE sits exactly ON the
    //  tubercle surface, so a full hemisphere protrudes and the tangency
    //  circle is a hard normal break the ink pass draws as a ring - no
    //  collar geometry needed. The old cluster pinned all eight to a flat
    //  z = 0.36 plane, which left FOUR of them entirely inside the carapace
    //  (q = 0.596 and 0.694) and the rest protruding 0.003 to 0.020.
    //
    //  The other half is size hierarchy: the two posterior median eyes are
    //  r = 0.076, roughly 5.6x the projected area of the old beads and 36%
    //  of the head half-width. They are the recognition cue, not the count.
    //  Keep flag = 1 on every eye - shaders.js:599 keys the glossy black
    //  material (rough 0.09, spec 2.2) on it, and that specular highlight is
    //  the one genuinely BRIGHT thing on this animal.
    for (s = -1; s <= 1; s += 2) {
      // posterior median: the two big forward-facing eyes
      b.reset().setPart(P.HEAD, 0, s, 1).at(s * 0.0968, 0.5121, 0.5479).scl(0.076, 0.076, 0.068);
      b.ellipsoid(9, 7);
      // posterior lateral: up on the top corners, so the face survives a
      // near-overhead look and shows as bumps on the head outline from side on
      b.reset().setPart(P.HEAD, 0, s, 1).at(s * 0.1672, 0.5596, 0.3734).scl(0.042, 0.042, 0.038);
      b.ellipsoid(7, 5);
      // anterior row: four small ones low on the face, clear of the fangs
      b.reset().setPart(P.HEAD, 0, s, 1).at(s * 0.0420, 0.3874, 0.5405).scl(0.030, 0.030, 0.026);
      b.ellipsoid(6, 4);
      b.reset().setPart(P.HEAD, 0, s, 1).at(s * 0.1221, 0.3948, 0.5007).scl(0.028, 0.028, 0.025);
      b.ellipsoid(6, 4);
    }

    // --- CHELICERAE AND PEDIPALPS -------------------------------------
    for (s = -1; s <= 1; s += 2) {
      //  Paturon: a stout block hanging 0.149 below the face, anchored in
      //  the carapace so the join is a crease. The pair nearly meets at the
      //  midline, which gives one more line down the jaw. The old build had
      //  no paturon at all - just a bare 23:1 cone that read as a whisker.
      b.reset().setPart(LIMB, 0, s, 0).at(s * 0.098, 0.290, 0.455).scl(0.088, 0.115, 0.090);
      b.ellipsoid(8, 6);
      //  Fang: DOWN at 63 degrees (the old one was 30) and INWARD - note the
      //  -s x-term, the same convergence the beetle's jaws and the
      //  centipede's venom claws use. Splayed apart, a pair of appendages
      //  reads as two more legs; converged, it reads as a pincer. Tips land
      //  at x = +/-0.056, so they close without crossing.
      b.reset().setPart(LIMB, 0, s, 0).at(s * 0.095, 0.215, 0.470).rotFromAxis([-s * 0.28, -1.0, 0.42]);
      b.limb(0.155, 0.032, 0.006, 6, 2, 0, 1);

      //  PEDIPALPS. The mesh had none, and on a wolf spider they are the
      //  instant tell. They read for a reason that survives darkness: they
      //  are the only appendage that goes forward and DOWN while all eight
      //  legs arch UP, and they are thicker (0.046) than a leg's tibia
      //  (0.050 -> 0.030) at half the length, so they never read as a ninth
      //  leg. The clubbed tip reaches z = 0.93, filling the gap between the
      //  fangs at 0.53 and the front feet at 1.01.
      bone(s, [0.175, 0.330, 0.400], [0.290, 0.255, 0.640], 0.046, 0.034, 6, 2, 0, 0.5);
      bone(s, [0.290, 0.255, 0.640], [0.245, 0.130, 0.860], 0.034, 0.026, 6, 2, 0.5, 0.3);
      b.reset().setPart(LIMB, 0, s, 0).at(s * 0.240, 0.125, 0.880).scl(0.042, 0.038, 0.052);
      b.ellipsoid(7, 5);
    }

    // --- EIGHT LEGS ---------------------------------------------------
    //  Three segments: femur out and UP to a knee standing well clear of the
    //  back, tibia the long span back DOWN to an ankle, then a short tarsus
    //  lying along the sand at about 23 degrees. A spider stands on the
    //  LENGTH of its foot; the old two-segment leg speared the ground at 50
    //  degrees and terminated on a 0.010 needle, which at scale 0.62 is
    //  0.006 world units and simply aliased away.
    //
    //  Three separate fixes to the table itself:
    //  - knee heights all DIFFER (0.845 to 0.965). The old build used the
    //    literal 0.95 for every leg, so at the tank's near-side-on default
    //    camera the knees sat on one flat horizontal like a picket fence -
    //    and the old `spread` repeated 0.95 at index 1 and 3, so two legs
    //    per side projected onto exactly the same screen line at yaw 0.
    //  - feet are NOT evenly spaced. The old z were 0.983 / 0.333 / -0.318 /
    //    -0.968, gaps of 0.650 / 0.651 / 0.650: a comb, not a spider. These
    //    group 2 + 2, with the middle gap about twice the outer ones.
    //  - length order is IV > I > II > III (1.995 / 1.917 / 1.790 / 1.716),
    //    the Lycosid order; leg IV is the long propulsive one. The old build
    //    ran I > IV > II > III.
    //         hip                        knee                       ankle                       foot
    var LEGS = [
      { h: [0.225, 0.375,  0.255], k: [0.520, 0.965,  0.560], a: [0.865, 0.095,  0.850], f: [0.975, 0.014,  1.010] },
      { h: [0.235, 0.380,  0.130], k: [0.620, 0.895,  0.240], a: [1.070, 0.095,  0.440], f: [1.205, 0.014,  0.560] },
      { h: [0.225, 0.375, -0.020], k: [0.600, 0.845, -0.230], a: [1.045, 0.095, -0.380], f: [1.175, 0.014, -0.500] },
      { h: [0.155, 0.370, -0.165], k: [0.520, 0.940, -0.600], a: [0.895, 0.095, -0.900], f: [1.020, 0.014, -1.060] }
    ];
    for (L = 0; L < 8; L++) {
      var side = L < 4 ? 1 : -1;
      var g = LEGS[L % 4];
      // femur: out and UP. 0.078 -> 0.052 over 0.64-0.80, about 11:1.
      bone(side, g.h, g.k, 0.078, 0.052, 7, 2, 0, 0.35);
      //  PATELLA. The single most valuable bead on the animal. The old leg
      //  had NO radius step at the knee - femur ended at 0.038 and tibia
      //  began at 0.038 - so a 100-degree bend was a kink in a constant tube
      //  with a faceted mitre in it, which is the definition of wire. At
      //  0.066 it is 27% fatter than either tube, and because these stand
      //  0.19-0.31 above the highest point of the body, eight of them are a
      //  row of knuckles ON THE OUTLINE, which is the one place contrast
      //  does not have to fight a multiply on a near-black surface.
      b.reset().setPart(LIMB, 0, side, 0).at(side * g.k[0], g.k[1], g.k[2]).scl(0.066, 0.066, 0.066);
      b.ellipsoid(6, 5);
      // tibia: back DOWN. 0.050 -> 0.030 over ~0.94, about 24:1 - was 50:1.
      bone(side, g.k, g.a, 0.050, 0.030, 6, 2, 0.35, 0.40);
      //  tarsus: the only part allowed to go thin, and it is short. Near
      //  horizontal along the sand, which is what gives the leg a stance
      //  instead of a point, and eight ground-contact lines for the ink.
      bone(side, g.a, g.f, 0.028, 0.013, 5, 1, 0.75, 0.25);
    }

    return b;
  };

  // ------------------------------------------------------------------
  //  ENVIRONMENT
  // ------------------------------------------------------------------
  //  Surface heightfield patch (the soil top / terrarium landscape)
  G.buildSurface = function (w, d, nx, nz, heightFn) {
    var b = new Builder();
    var base = b.vertCount();
    for (var j = 0; j <= nz; j++) {
      for (var i = 0; i <= nx; i++) {
        var u = i / nx, v = j / nz;
        var x = (u - 0.5) * w, z = (v - 0.5) * d;
        var y = heightFn(x, z);
        var e = 0.12;
        var hx = heightFn(x + e, z), hz = heightFn(x, z + e);
        var nX = -(hx - y) / e, nZ = -(hz - y) / e;
        var l = Math.sqrt(nX * nX + 1 + nZ * nZ);
        b.vert(x, y, z, nX / l, 1 / l, nZ / l, u * 8, v * 8);
      }
    }
    for (j = 0; j < nz; j++) for (i = 0; i < nx; i++) {
      var a = base + j * (nx + 1) + i, bb = a + nx + 1;
      b.quad(a, bb, bb + 1, a + 1);
    }
    return b;
  };

  //  Glass panels of a vitrine (open top), inward + outward faces
  G.buildGlassBox = function (hx, hy, hz) {
    var b = new Builder();
    b.reset().setPart(0, 0, 0, 0);
    var sides = [
      { n: [0, 0, 1], c: [0, 0, hz], u: [1, 0, 0], v: [0, 1, 0], su: hx, sv: hy },
      { n: [0, 0, -1], c: [0, 0, -hz], u: [1, 0, 0], v: [0, 1, 0], su: hx, sv: hy },
      { n: [1, 0, 0], c: [hx, 0, 0], u: [0, 0, 1], v: [0, 1, 0], su: hz, sv: hy },
      { n: [-1, 0, 0], c: [-hx, 0, 0], u: [0, 0, 1], v: [0, 1, 0], su: hz, sv: hy }
    ];
    for (var k = 0; k < sides.length; k++) {
      var S = sides[k];
      var base = b.vertCount();
      for (var q = 0; q < 4; q++) {
        var uu = (q === 1 || q === 2) ? 1 : -1;
        var vv = (q >= 2) ? 1 : -1;
        b.vert(S.c[0] + S.u[0] * uu * S.su + S.v[0] * vv * S.sv,
          S.c[1] + S.u[1] * uu * S.su + S.v[1] * vv * S.sv,
          S.c[2] + S.u[2] * uu * S.su + S.v[2] * vv * S.sv,
          S.n[0], S.n[1], S.n[2], (uu + 1) * 0.5, (vv + 1) * 0.5);
      }
      b.quad(base, base + 1, base + 2, base + 3);
    }
    return b;
  };

  //  Wooden / metal frame rails around a vitrine
  G.buildFrame = function (hx, hy, hz, t) {
    var b = new Builder();
    var bars = [];
    var ys = [-hy, hy];
    for (var yi = 0; yi < 2; yi++) {
      var y = ys[yi];
      bars.push([0, y, hz, hx + t, t, t], [0, y, -hz, hx + t, t, t]);
      bars.push([hx, y, 0, t, t, hz + t], [-hx, y, 0, t, t, hz + t]);
    }
    for (var sx = -1; sx <= 1; sx += 2) for (var sz = -1; sz <= 1; sz += 2) {
      bars.push([sx * hx, 0, sz * hz, t, hy, t]);
    }
    for (var i = 0; i < bars.length; i++) {
      var B = bars[i];
      b.reset().setPart(0, 0, 0, 0).at(B[0], B[1], B[2]);
      b.boxFaces(B[3], B[4], B[5], false);
    }
    return b;
  };

  //  Connection tube between two farms (glass pipe along a bezier)
  G.buildTube = function (segments, radialSegs) {
    // unit tube along +Z from 0..1 ; the shader bends it via uTubeCtrl
    var b = new Builder();
    var base = b.vertCount();
    for (var j = 0; j <= segments; j++) {
      var t = j / segments;
      for (var i = 0; i <= radialSegs; i++) {
        var th = i / radialSegs * M.TAU;
        b.setPart(0, t, 0, 0);
        b.vert(Math.cos(th), Math.sin(th), t, Math.cos(th), Math.sin(th), 0, i / radialSegs, t);
      }
    }
    for (j = 0; j < segments; j++) for (i = 0; i < radialSegs; i++) {
      var a = base + j * (radialSegs + 1) + i, bb = a + radialSegs + 1;
      b.quad(a, bb, bb + 1, a + 1);
    }
    return b;
  };

  //  simple quad for billboards / decals
  //  A rounded blob - the body of one water particle. Subdivided
  //  icosahedron: 42 verts / 80 tris at subdiv 1, which is the cheapest
  //  shape that still reads as a droplet rather than a facet.
  G.buildBlob = function (subdiv) {
    var t = (1 + Math.sqrt(5)) / 2;
    var v = [
      [-1, t, 0], [1, t, 0], [-1, -t, 0], [1, -t, 0],
      [0, -1, t], [0, 1, t], [0, -1, -t], [0, 1, -t],
      [t, 0, -1], [t, 0, 1], [-t, 0, -1], [-t, 0, 1]
    ];
    var f = [
      [0, 11, 5], [0, 5, 1], [0, 1, 7], [0, 7, 10], [0, 10, 11],
      [1, 5, 9], [5, 11, 4], [11, 10, 2], [10, 7, 6], [7, 1, 8],
      [3, 9, 4], [3, 4, 2], [3, 2, 6], [3, 6, 8], [3, 8, 9],
      [4, 9, 5], [2, 4, 11], [6, 2, 10], [8, 6, 7], [9, 8, 1]
    ];
    var i, j;
    for (i = 0; i < v.length; i++) {
      var l = Math.sqrt(v[i][0] * v[i][0] + v[i][1] * v[i][1] + v[i][2] * v[i][2]);
      v[i][0] /= l; v[i][1] /= l; v[i][2] /= l;
    }
    for (var s = 0; s < (subdiv || 0); s++) {
      var mid = {}, nf = [];
      function midpoint(a, b) {
        var k = a < b ? a + '_' + b : b + '_' + a;
        if (mid[k] !== undefined) return mid[k];
        var m = [(v[a][0] + v[b][0]) / 2, (v[a][1] + v[b][1]) / 2, (v[a][2] + v[b][2]) / 2];
        var ml = Math.sqrt(m[0] * m[0] + m[1] * m[1] + m[2] * m[2]);
        m[0] /= ml; m[1] /= ml; m[2] /= ml;
        v.push(m); mid[k] = v.length - 1; return mid[k];
      }
      for (i = 0; i < f.length; i++) {
        var a = f[i][0], b = f[i][1], c = f[i][2];
        var ab = midpoint(a, b), bc = midpoint(b, c), ca = midpoint(c, a);
        nf.push([a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca]);
      }
      f = nf;
    }
    var bd = new Builder();
    bd.reset().setPart(0, 0, 0, 0);
    var base = bd.vertCount();
    for (i = 0; i < v.length; i++) {
      var u = 0.5 + Math.atan2(v[i][2], v[i][0]) / (2 * Math.PI);
      var vv = 0.5 - Math.asin(v[i][1]) / Math.PI;
      bd.vert(v[i][0], v[i][1], v[i][2], v[i][0], v[i][1], v[i][2], u, vv);
    }
    for (i = 0; i < f.length; i++) bd.tri(base + f[i][0], base + f[i][1], base + f[i][2]);
    return bd;
  };

  //  Flat annulus in XZ - the aim contour. UV.x runs 0..1 around the ring
  //  and UV.y is 0 at the inner edge, 1 at the outer, so the shader can
  //  dash it and feather it without any extra attributes.
  G.buildRing = function (segs, inner, outer) {
    var b = new Builder();
    b.reset().setPart(0, 0, 0, 0);
    var base = b.vertCount();
    for (var i = 0; i <= segs; i++) {
      var a = i / segs * Math.PI * 2;
      var ca = Math.cos(a), sa = Math.sin(a);
      b.vert(ca * inner, 0, sa * inner, 0, 1, 0, i / segs, 0);
      b.vert(ca * outer, 0, sa * outer, 0, 1, 0, i / segs, 1);
    }
    for (i = 0; i < segs; i++) {
      var o = base + i * 2;
      b.quad(o, o + 2, o + 3, o + 1);
    }
    return b;
  };

  G.buildQuad = function () {
    var b = new Builder();
    var base = b.vertCount();
    b.vert(-1, -1, 0, 0, 0, 1, 0, 0);
    b.vert(1, -1, 0, 0, 0, 1, 1, 0);
    b.vert(1, 1, 0, 0, 0, 1, 1, 1);
    b.vert(-1, 1, 0, 0, 0, 1, 0, 1);
    b.quad(base, base + 1, base + 2, base + 3);
    return b;
  };

  //  unit cube box
  G.buildBox = function (hx, hy, hz, inside) {
    var b = new Builder();
    b.reset().setPart(0, 0, 0, 0);
    b.boxFaces(hx, hy, hz, inside);
    return b;
  };

  AF.G = G;
})(window.AF = window.AF || {});
