/* =============================================================
   FORMICARIUM :: DEEP COLONY
   shaders.js - scene GLSL (ES 3.00)
   ============================================================= */
(function (AF) {
  'use strict';
  var S = {};

  // ==================================================================
  //  COMMON CHUNKS
  // ==================================================================
  S.HEAD = [
    '#version 300 es',
    'precision highp float;',
    'precision highp int;',
    'precision highp sampler3D;',
    'precision highp sampler2DShadow;'
  ].join('\n');

  S.NOISE = [
    'float hash11(float p){ p=fract(p*0.1031); p*=p+33.33; p*=p+p; return fract(p); }',
    'float hash12(vec2 p){ vec3 p3=fract(vec3(p.xyx)*0.1031); p3+=dot(p3,p3.yzx+33.33); return fract((p3.x+p3.y)*p3.z); }',
    'vec3 hash33(vec3 p){ p=vec3(dot(p,vec3(127.1,311.7,74.7)),dot(p,vec3(269.5,183.3,246.1)),dot(p,vec3(113.5,271.9,124.6)));',
    '  return fract(sin(p)*43758.5453123); }',
    'float hash13(vec3 p){ p=fract(p*0.3183099+vec3(0.1,0.2,0.3)); p*=17.0; return fract(p.x*p.y*p.z*(p.x+p.y+p.z)); }',
    'float vnoise(vec3 x){',
    '  vec3 i=floor(x), f=fract(x); f=f*f*(3.0-2.0*f);',
    '  return mix(mix(mix(hash13(i+vec3(0,0,0)),hash13(i+vec3(1,0,0)),f.x),',
    '                 mix(hash13(i+vec3(0,1,0)),hash13(i+vec3(1,1,0)),f.x),f.y),',
    '             mix(mix(hash13(i+vec3(0,0,1)),hash13(i+vec3(1,0,1)),f.x),',
    '                 mix(hash13(i+vec3(0,1,1)),hash13(i+vec3(1,1,1)),f.x),f.y),f.z);',
    '}',
    'float fbm(vec3 p, int oct){ float a=0.5,s=0.0; for(int i=0;i<8;i++){ if(i>=oct)break; s+=a*vnoise(p); p*=2.03; a*=0.5;} return s; }',
    'float ridged(vec3 p, int oct){ float a=0.5,s=0.0; for(int i=0;i<8;i++){ if(i>=oct)break; s+=a*(1.0-abs(vnoise(p)*2.0-1.0)); p*=2.11; a*=0.5;} return s; }',
    'float worley(vec3 p){',
    '  vec3 i=floor(p), f=fract(p); float d=1.0;',
    '  for(int z=-1;z<=1;z++)for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){',
    '    vec3 g=vec3(float(x),float(y),float(z)); vec3 o=hash33(i+g);',
    '    d=min(d,length(g+o-f)); }',
    '  return d;',
    '}'
  ].join('\n');

  S.LIGHTING = [
    '#define MAXL 16',
    'uniform vec4 uLightPos[MAXL];   // xyz, radius',
    'uniform vec4 uLightCol[MAXL];   // rgb, intensity',
    'uniform int  uLightCount;',
    'uniform vec3 uSunDir;',
    'uniform vec3 uSunCol;',
    'uniform vec3 uSkyCol;',
    'uniform vec3 uGndCol;',
    'uniform vec3 uCamPos;',
    '',
    'float D_GGX(float NoH, float a){ float a2=a*a; float d=NoH*NoH*(a2-1.0)+1.0; return a2/(3.14159265*d*d+1e-7); }',
    'float V_Smith(float NoV,float NoL,float a){ float a2=a*a;',
    '  float gv=NoL*sqrt(NoV*NoV*(1.0-a2)+a2); float gl=NoV*sqrt(NoL*NoL*(1.0-a2)+a2);',
    '  return 0.5/max(gv+gl,1e-5); }',
    'vec3 F_Schlick(vec3 f0,float u){ float f=pow(1.0-u,5.0); return f0+(1.0-f0)*f; }',
    '',
    'uniform float uToon;   // 1 = storybook shading: banded light, soft speculars',
    'vec3 shadeDirect(vec3 N,vec3 V,vec3 L,vec3 lc,vec3 albedo,float rough,float metal,float spec){',
    '  vec3 H=normalize(L+V);',
    '  float NoL=max(dot(N,L),0.0);',
    '  if(NoL<=0.0) return vec3(0.0);',
    '  float NoV=max(dot(N,V),1e-4), NoH=max(dot(N,H),0.0), VoH=max(dot(V,H),0.0);',
    '  float a=max(rough*rough,0.0025);',
    '  vec3 f0=mix(vec3(0.04*spec),albedo,metal);',
    '  vec3 F=F_Schlick(f0,VoH);',
    '  vec3 specC=F*D_GGX(NoH,a)*V_Smith(NoV,NoL,a);',
    '  vec3 kd=(1.0-F)*(1.0-metal);',
    '  if(uToon>0.5){',
    '    // three soft bands instead of a smooth falloff: wide enough to stay',
    '    // readable on tiny ants, never hard-edged enough to look posterised',
    '    float b = smoothstep(0.02,0.30,NoL)*0.42',
    '            + smoothstep(0.34,0.56,NoL)*0.34',
    '            + smoothstep(0.62,0.84,NoL)*0.24;',
    '    NoL = 0.30 + 0.85*b;',
    '    specC *= 0.22;',
    '  }',
    '  return (kd*albedo/3.14159265+specC)*lc*NoL;',
    '}',
    'vec3 ambientIBL(vec3 N,vec3 V,vec3 albedo,float rough,float metal,float ao){',
    '  float up=N.y*0.5+0.5;',
    '  vec3 irr=mix(uGndCol,uSkyCol,up);',
    '  vec3 R=reflect(-V,N);',
    '  vec3 refl=mix(uGndCol,uSkyCol,R.y*0.5+0.5);',
    '  float NoV=max(dot(N,V),1e-4);',
    '  vec3 f0=mix(vec3(0.04),albedo,metal);',
    '  vec3 F=F_Schlick(f0,NoV)*(1.0-rough*0.85);',
    '  return (albedo*(1.0-metal)*irr*ao + refl*F*mix(ao,1.0,0.35));',
    '}',
    'vec3 pointLights(vec3 P,vec3 N,vec3 V,vec3 albedo,float rough,float metal,float spec){',
    '  vec3 acc=vec3(0.0);',
    '  for(int i=0;i<MAXL;i++){',
    '    if(i>=uLightCount) break;',
    '    vec3 d=uLightPos[i].xyz-P; float dist=length(d);',
    '    float r=uLightPos[i].w;',
    '    if(dist>r) continue;',
    '    float att=clamp(1.0-dist/r,0.0,1.0); att*=att;',
    '    acc+=shadeDirect(N,V,d/max(dist,1e-4),uLightCol[i].rgb*uLightCol[i].w*att,albedo,rough,metal,spec);',
    '  }',
    '  return acc;',
    '}'
  ].join('\n');

  S.SHADOW = [
    'uniform sampler2D uShadowMap;',
    'uniform mat4 uLightVP;',
    'uniform vec2 uShadowTexel;',
    'float shadowAt(vec3 P,float NoL){',
    '  vec4 lp=uLightVP*vec4(P,1.0);',
    '  vec3 sc=lp.xyz/lp.w*0.5+0.5;',
    '  if(sc.z>1.0) return 1.0;',
    '  // fade out toward the edge of the map so its border is invisible',
    '  vec2 q=abs(sc.xy-0.5)*2.0;',
    '  float edge=1.0-smoothstep(0.80,0.99,max(q.x,q.y));',
    '  if(edge<=0.001) return 1.0;',
    '  float bias=max(0.0016*(1.0-NoL),0.00035);',
    '  float s=0.0;',
    '  for(int y=-1;y<=1;y++){ for(int x=-1;x<=1;x++){',
    '    float d=texture(uShadowMap,sc.xy+vec2(float(x),float(y))*uShadowTexel*1.35).r;',
    '    s+=(sc.z-bias>d)?0.0:1.0;',
    '  }}',
    '  return mix(1.0,s/9.0,edge);',
    '}'
  ].join('\n');

  S.SDFLIB = [
    'uniform sampler3D uSDF;',
    'uniform vec3 uSdfMin;',
    'uniform vec3 uSdfMax;',
    'float sdfAt(vec3 p){',
    '  vec3 uvw=(p-uSdfMin)/(uSdfMax-uSdfMin);',
    '  vec3 cl=clamp(uvw,vec3(0.0),vec3(1.0));',
    '  float d=texture(uSDF,cl).r;',
    '  float outside=length((uvw-cl)*(uSdfMax-uSdfMin));',
    '  return d+outside;',
    '}',
    'vec3 sdfNormal(vec3 p,float e){',
    '  vec2 k=vec2(1.0,-1.0);',
    '  return normalize(k.xyy*sdfAt(p+k.xyy*e)+k.yyx*sdfAt(p+k.yyx*e)+',
    '                   k.yxy*sdfAt(p+k.yxy*e)+k.xxx*sdfAt(p+k.xxx*e));',
    '}',
    // d0 is the field value at p: subtracting it removes the half-texel
    // bias baked into the volume, so a flat exposed face reads as unoccluded.
    'float sdfAO(vec3 p,vec3 n,float d0){',
    '  float occ=0.0,sca=1.0;',
    '  for(int i=0;i<5;i++){',
    '    float h=0.09+0.62*float(i)*float(i)*0.30;',
    '    float d=sdfAt(p+n*h)-d0;',
    '    occ+=max(h-d,0.0)*sca; sca*=0.70;',
    '  }',
    '  return clamp(1.0-1.05*occ,0.0,1.0);',
    '}'
  ].join('\n');

  // surface height : MUST match AF.World.surfaceH in world.js
  S.SURFACE = [
    'float surfaceH(vec2 q){',
    '  float h=0.0;',
    '  h+=sin(q.x*0.35+1.3)*0.55;',
    '  h+=sin(q.y*0.41-0.7)*0.48;',
    '  h+=sin((q.x*0.23+q.y*0.19)+2.1)*0.75;',
    '  h+=sin(q.x*0.87-q.y*0.61)*0.22;',
    '  h+=sin(q.x*1.7+q.y*1.3+0.5)*0.09;',
    '  return h;',
    '}'
  ].join('\n');

  // ==================================================================
  //  1. SDF BAKE  (renders one Z-slice of the 3D distance field)
  // ==================================================================
  S.BAKE_FS = [
    S.HEAD,
    S.NOISE,
    S.SURFACE,
    'uniform sampler2D uSegTex;   // 2 texels per capsule: (A.xyz,rA) (B.xyz,rB)',
    'uniform int uSegCount;',
    'uniform vec3 uBoxMin;',
    'uniform vec3 uBoxMax;',
    'uniform vec3 uGrid;',
    'uniform float uLayer;',
    'uniform float uTopY;',
    'uniform float uTexW;',
    'uniform vec2 uSurfOrigin;',
    'out vec4 oCol;',
    'float sdCapsule(vec3 p,vec3 a,vec3 b,float ra,float rb){',
    '  vec3 pa=p-a, ba=b-a;',
    '  float h=clamp(dot(pa,ba)/max(dot(ba,ba),1e-6),0.0,1.0);',
    '  return length(pa-ba*h)-mix(ra,rb,h);',
    '}',
    'void main(){',
    '  vec3 cell=vec3(gl_FragCoord.xy,uLayer+0.5);',
    '  vec3 uvw=cell/uGrid;',
    '  vec3 p=mix(uBoxMin,uBoxMax,uvw);',
    '  // soil slab: inside box, below the sculpted top surface',
    '  vec3 c=(uBoxMin+uBoxMax)*0.5, he=(uBoxMax-uBoxMin)*0.5;',
    '  vec3 q=abs(p-c)-he;',
    '  float dBox=length(max(q,0.0))+min(max(q.x,max(q.y,q.z)),0.0);',
    '  float top=p.y-(uTopY+surfaceH(p.xz-uSurfOrigin));',
    '  float d=max(dBox,top);',
    '  // carve tunnels',
    '  float dig=1e5;',
    '  for(int i=0;i<512;i++){',
    '    if(i>=uSegCount) break;',
    '    float fx=(float(i*2)+0.5)/uTexW;',
    '    float fx2=(float(i*2+1)+0.5)/uTexW;',
    '    vec4 A=texture(uSegTex,vec2(fx,0.5));',
    '    vec4 B=texture(uSegTex,vec2(fx2,0.5));',
    '    dig=min(dig,sdCapsule(p,A.xyz,B.xyz,A.w,B.w));',
    '  }',
    '  // ants do not bore perfect cylinders: roughen every excavated wall',
    '  float rough=(fbm(p*0.62,4)-0.5)*0.85+(fbm(p*2.3,3)-0.5)*0.26;',
    '  dig+=rough*0.55;',
    '  d=max(d,-dig);',
    '  // and the natural top surface gets a little grit too',
    '  d+=(fbm(p*1.35+vec3(19.0),3)-0.5)*0.10;',
    '  oCol=vec4(clamp(d,-3.0,3.0),0.0,0.0,1.0);',
    '}'
  ].join('\n');

  // ==================================================================
  //  2. SOIL  (volumetric raymarch inside the vitrine)
  // ==================================================================
  S.SOIL_VS = [
    S.HEAD,
    'in vec3 aPos;',
    'uniform mat4 uVP;',
    'uniform vec3 uBoxCenter;',
    'uniform vec3 uBoxHalf;',
    'out vec3 vWorld;',
    'void main(){',
    '  vec3 p=uBoxCenter+aPos*uBoxHalf;',
    '  vWorld=p;',
    '  gl_Position=uVP*vec4(p,1.0);',
    '}'
  ].join('\n');

  S.SOIL_FS = [
    S.HEAD,
    S.NOISE,
    S.LIGHTING,
    S.SHADOW,
    S.SDFLIB,
    'in vec3 vWorld;',
    'uniform mat4 uVP;',
    'uniform vec3 uBoxCenter;',
    'uniform vec3 uBoxHalf;',
    'uniform vec3 uSoilA;',
    'uniform vec3 uSoilB;',
    'uniform vec3 uSoilTop;',
    'uniform float uWetness;',
    'uniform float uGrainScale;',
    'uniform float uTime;',
    'uniform float uQuality;',
    'uniform float uTopY;',
    'uniform float uHygiene;',
    'uniform float uMold;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    '',
    'vec2 boxT(vec3 ro,vec3 rd,vec3 c,vec3 he){',
    '  vec3 m=1.0/(rd+1e-9); vec3 n=m*(ro-c); vec3 k=abs(m)*he;',
    '  vec3 t1=-n-k, t2=-n+k;',
    '  return vec2(max(max(t1.x,t1.y),t1.z), min(min(t2.x,t2.y),t2.z));',
    '}',
    '',
    'vec3 soilAlbedo(vec3 p,vec3 n,out float rough,out float spec){',
    '  float depth=clamp((uTopY-p.y)/max(uBoxHalf.y*1.6,1.0),0.0,1.0);',
    '  if(uToon>0.5){',
    '    //  Storybook soil: a few flat bands of colour with hand-wobbled',
    '    //  boundaries, big soft blotches, and nothing else. Photoreal grit,',
    '    //  worley pebbles and mineral flecks all read as noise at this scale',
    '    //  and are exactly what stopped it looking drawn.',
    '    float wob=fbm(vec3(p.x*0.16,p.y*0.05,p.z*0.16),3)-0.5;',
    '    float band=depth+wob*0.16;',
    '    vec3 topCol =uSoilTop*1.42;',
    '    vec3 midCol =mix(uSoilTop,uSoilA,0.62)*1.30;',
    '    vec3 deepCol=mix(uSoilA,uSoilB,0.45)*1.22;',
    '    vec3 coreCol=uSoilB*1.30;',
    '    vec3 col=topCol;',
    '    col=mix(col,midCol ,smoothstep(0.055,0.105,band));',
    '    col=mix(col,deepCol,smoothstep(0.300,0.360,band));',
    '    col=mix(col,coreCol,smoothstep(0.640,0.700,band));',
    '    // a couple of big soft patches so the flats are not dead',
    '    float blot=fbm(vec3(p*0.085)+vec3(11.0),3);',
    '    col*=0.94+0.13*smoothstep(0.35,0.72,blot);',
    '    float blot2=fbm(vec3(p*0.21)+vec3(41.0),2);',
    '    col*=0.97+0.07*blot2;',
    '    // ink the strata lines themselves, like a pencil edge',
    '    float e1=smoothstep(0.012,0.0,abs(band-0.080));',
    '    float e2=smoothstep(0.012,0.0,abs(band-0.330));',
    '    float e3=smoothstep(0.012,0.0,abs(band-0.670));',
    '    col*=1.0-0.20*max(e1,max(e2,e3));',
    '    rough=0.92; spec=0.18;',
    '    return col;',
    '  }',
    '',
    '  //  ---------------- STORYBOOK SOIL ----------------',
    '  //  Flat painted bands instead of photoreal mud. Everything here is',
    '  //  deliberately low frequency: a child should read "ground" instantly,',
    '  //  and fine grain would fight the ink outlines drawn in post.',
    '  if(uToon>0.5){',
    '    float warpT=fbm(vec3(p.x*0.085,p.y*0.05,p.z*0.085),2);',
    '    float d2=clamp(depth+(warpT-0.5)*0.26,0.0,1.0);',
    '    vec3 c1=uSoilTop*vec3(1.55,1.46,1.28);',
    '    vec3 c2=uSoilA*vec3(1.85,1.62,1.32);',
    '    vec3 c3=uSoilB*vec3(2.30,1.94,1.52);',
    '    vec3 tc=c1;',
    '    tc=mix(tc,c2,smoothstep(0.09,0.15,d2));',
    '    tc=mix(tc,c3,smoothstep(0.43,0.51,d2));',
    '    // wide painted patches, stepped so they look brushed on',
    '    float blob=fbm(p*0.30+vec3(7.0),2);',
    '    tc*=0.90+0.22*(floor(blob*4.0)/4.0);',
    '    // small drawn pebbles, gathered in patches rather than evenly spotted',
    '    float clump=smoothstep(0.54,0.70,fbm(p*0.20+vec3(31.0),2));',
    '    float cell=worley(p*1.75+vec3(13.0));',
    '    float peb=smoothstep(0.155,0.10,cell)*clump;',
    '    float ring=(smoothstep(0.215,0.155,cell))*clump-peb;',
    '    tc=mix(tc,vec3(0.47,0.43,0.39),peb*0.70);',
    '    tc*=1.0-max(ring,0.0)*0.30;',
    '    // damp lip just under the surface keeps the top edge readable',
    '    tc*=1.0-0.16*smoothstep(0.055,0.0,depth);',
    '    rough=0.96; spec=0.08;',
    '    return tc;',
    '  }',
    '',
    '  vec3 ap=p*uGrainScale*2.6;',
    '  float g1=fbm(ap*0.75,5);',
    '  float g2=fbm(ap*3.4+17.0,4);',
    '  float g3=fbm(ap*11.0-31.0,2);',
    '  float grains=worley(ap*3.1);',
    '  vec3 col=mix(uSoilTop,uSoilA,smoothstep(0.02,0.35,depth));',
    '  col=mix(col,uSoilB,smoothstep(0.30,0.95,depth)*0.85);',
    '  // sediment strata: the reason a real cross-section reads as ground',
    '  float warp=fbm(vec3(p.x*0.11,p.y*0.05,p.z*0.11),3);',
    '  float band=p.y*0.36+warp*2.1;',
    '  float s1=sin(band*3.1)*0.5+0.5;',
    '  float s2=sin(band*7.7+1.7)*0.5+0.5;',
    '  col*=0.80+0.34*s1+0.13*s2;',
    '  col=mix(col,col*vec3(1.16,1.02,0.86),smoothstep(0.62,0.92,s1));',
    '  col=mix(col,col*vec3(0.80,0.86,0.92),smoothstep(0.70,0.95,s2)*0.7);',
    '  col*=0.60+0.85*g1;',
    '  col*=0.82+0.36*g3;',
    '  col*=0.86+0.30*fbm(ap*9.0+vec3(53.0),3);',   // micro grain, holds up close
    '  col*=0.90+0.22*fbm(ap*26.0,2);',
    '  col+=vec3(0.10,0.085,0.062)*smoothstep(0.55,0.95,g2);',
    '  // mineral flecks',
    '  float fleck=smoothstep(0.90,0.965,1.0-grains);',
    '  col+=vec3(0.30,0.28,0.26)*fleck*0.22;',
    '  // grit and the occasional pebble, sliced open by the pane',
    '  float gritCell=worley(p*4.6+vec3(4.0));',
    '  float grit=smoothstep(0.15,0.05,gritCell);',
    '  float pebCell=worley(p*1.35+vec3(21.0));',
    '  float peb=smoothstep(0.11,0.035,pebCell)*step(0.62,fbm(p*0.9+vec3(9.0),2)+0.25);',
    '  float stone=max(grit*0.75,peb);',
    '  vec3 stoneCol=mix(vec3(0.175,0.165,0.155),vec3(0.30,0.275,0.245),fbm(p*9.0,3));',
    '  stoneCol*=0.70+0.55*fbm(p*26.0,2);',
    '  col=mix(col,stoneCol,stone*0.92);',
    '  // dark halo where a stone parts the soil around it',
    '  col*=1.0-0.28*smoothstep(0.17,0.11,gritCell)*(1.0-grit);',
    '  col*=1.0-0.34*smoothstep(0.135,0.09,pebCell)*(1.0-peb);',
    '  // organic litter near the top',
    '  float litter=smoothstep(0.14,0.0,depth)*smoothstep(0.5,0.85,g2);',
    '  col=mix(col,vec3(0.20,0.145,0.075),litter*0.55);',
    '  // root filaments',
    '  float root=smoothstep(0.72,0.85,ridged(ap*0.6+vec3(3.0),3));',
    '  col=mix(col,vec3(0.13,0.10,0.06),root*0.5*(1.0-depth*0.5));',
    '  // mold blooms when hygiene collapses',
    '  float mold=smoothstep(0.55,0.85,fbm(ap*0.45+uTime*0.01,3))*uMold;',
    '  col=mix(col,vec3(0.30,0.42,0.20),mold*0.75);',
    '  rough=mix(0.94,0.62,uWetness*(0.4+0.6*depth))-fleck*0.35-stone*0.30;',
    '  spec=0.35+uWetness*0.9+fleck*1.4+stone*1.1;',
    '  return col;',
    '}',
    '',
    'void main(){',
    '  vec3 ro=uCamPos;',
    '  vec3 rd=normalize(vWorld-uCamPos);',
    '  vec3 im=1.0/(rd+1e-9);',
    '  vec3 nn=im*(ro-uBoxCenter);',
    '  vec3 kk=abs(im)*uBoxHalf;',
    '  vec3 tt1=-nn-kk, tt2=-nn+kk;',
    '  float tN=max(max(tt1.x,tt1.y),tt1.z);',
    '  float tF=min(min(tt2.x,tt2.y),tt2.z);',
    '  if(tF<0.0||tN>tF) discard;',
    '  // which pane did the ray enter through - that face is the cross-section',
    '  vec3 faceN=-sign(rd)*step(tt1.yzx,tt1.xyz)*step(tt1.zxy,tt1.xyz);',
    '  float t=max(tN,0.0);',
    '  float tmax=tF;',
    '  vec3 p=ro+rd*t;',
    '  bool hit=false; bool onPane=false;',
    '  float d=sdfAt(p);',
    '  if(d<=0.004 && tN>0.0){',
    '    // the ray starts buried: we are looking straight at packed soil',
    '    hit=true; onPane=true;',
    '  } else {',
    '    int STEPS=int(mix(56.0,120.0,uQuality));',
    '    for(int i=0;i<128;i++){',
    '      if(i>=STEPS) break;',
    '      p=ro+rd*t;',
    '      d=sdfAt(p);',
    '      if(d<0.008){ hit=true; break; }',
    '      t+=max(d*0.85,0.010);',
    '      if(t>tmax) break;',
    '    }',
    '  }',
    '  if(!hit) discard;',
    '  vec3 N = onPane ? faceN : sdfNormal(p,0.055);',
    '  // two octaves of detail normal: clods, then grain',
    '  vec3 dn=vec3(fbm(p*4.4+vec3(11.0),3)-fbm(p*4.4-vec3(11.0),3),',
    '               fbm(p*4.4+vec3(23.0),3)-fbm(p*4.4-vec3(23.0),3),',
    '               fbm(p*4.4+vec3(37.0),3)-fbm(p*4.4-vec3(37.0),3));',
    '  vec3 dn2=vec3(fbm(p*17.0+vec3(5.0),2)-fbm(p*17.0-vec3(5.0),2),',
    '                fbm(p*17.0+vec3(13.0),2)-fbm(p*17.0-vec3(13.0),2),',
    '                fbm(p*17.0+vec3(29.0),2)-fbm(p*17.0-vec3(29.0),2));',
    '  // storybook soil stays smooth: bumpy micro-relief fights the flat bands',
    '  float dnAmt = uToon>0.5 ? 0.22 : 0.85;',
    '  float dn2Amt = uToon>0.5 ? 0.0 : 0.55;',
    '  N=normalize(N+dn*dnAmt+dn2*dn2Amt);',
    '  float rough,spec;',
    '  vec3 albedo=soilAlbedo(p,N,rough,spec);',
    '  float ao=onPane?1.0:sdfAO(p,N,d);',
    '  if(onPane){',
    '    // a tunnel running just behind the pane shows through as a dark bloom',
    '    float sub=-3.0;',
    '    for(int i=1;i<=5;i++){ sub=max(sub,sdfAt(p-faceN*(float(i)*0.42))); }',
    '    ao*=1.0-0.62*smoothstep(-0.70,0.30,sub);',
    '  }',
    '  vec3 V=normalize(uCamPos-p);',
    '  float NoL=max(dot(N,uSunDir),0.0);',
    '  float sh=shadowAt(p,NoL);',
    '  // ants dig damp soil - darken freshly exposed walls slightly',
    '  vec3 col=shadeDirect(N,V,uSunDir,uSunCol,albedo,rough,0.0,spec)*mix(1.0,sh,0.8)*ao;',
    '  col+=ambientIBL(N,V,albedo,rough,0.0,ao);',
    '  col+=pointLights(p,N,V,albedo,rough,0.0,spec);',
    '  // the keeper leaves a lamp over the shelf: soft top-down fill',
    '  col+=albedo*uSkyCol*1.05*(0.45+0.55*max(N.y,0.0))*mix(0.35,1.0,ao);',
    '  // subtle depth fog inside the glass',
    '  float dist=length(p-uCamPos);',
    '  col*=1.0;',
    '  oColor=vec4(col,1.0);',
    '  oNormal=vec4(N*0.5+0.5,rough);',
    '  vec4 cp=uVP*vec4(p,1.0);',
    '  gl_FragDepth=(cp.z/cp.w)*0.5+0.5;',
    '}'
  ].join('\n');

  // ==================================================================
  //  3. INSTANCED CREATURES / PROPS
  // ==================================================================
  S.ANT_ANIM = [
    'const vec3 LEG_ATTACH[6]=vec3[6](',
    '  vec3( 0.085,0.15, 0.155), vec3( 0.095,0.145, 0.045), vec3( 0.090,0.14,-0.060),',
    '  vec3(-0.085,0.15, 0.155), vec3(-0.095,0.145, 0.045), vec3(-0.090,0.14,-0.060));',
    'const float LEG_PHASE[6]=float[6](0.0,3.14159,0.0,3.14159,0.0,3.14159);',
    'void animPart(inout vec3 p,inout vec3 n,vec4 part,vec4 anim){',
    '  float pid=part.x, segT=part.y, side=part.z;',
    '  float ph=anim.x, amp=anim.y, atk=anim.z, extra=anim.w;',
    '  if(pid>=3.0&&pid<=8.0){',
    '    int li=int(pid+0.5)-3;',
    '    vec3 A=LEG_ATTACH[0];',
    '    for(int k=0;k<6;k++){ if(k==li) A=LEG_ATTACH[k]; }',
    '    float lph=ph+LEG_PHASE[0];',
    '    for(int k=0;k<6;k++){ if(k==li) lph=ph+LEG_PHASE[k]; }',
    '    float sw=sin(lph)*0.34*amp;',
    '    float lift=max(0.0,sin(lph+1.5708))*0.10*amp;',
    '    vec3 q=p-A;',
    '    float c=cos(sw), s=sin(sw);',
    '    q=vec3(c*q.x+s*q.z,q.y,-s*q.x+c*q.z);',
    '    n=vec3(c*n.x+s*n.z,n.y,-s*n.x+c*n.z);',
    '    q.y+=lift*smoothstep(0.0,0.55,segT)*1.15;',
    '    q.xz*=1.0+lift*0.35*segT;',
    '    p=A+q;',
    '  } else if(pid>8.5&&pid<9.5){',
    '    vec3 A=vec3(side*0.04,0.225,0.315);',
    '    float w1=sin(ph*0.85+side*1.7)*0.30+sin(ph*2.3+side)*0.10;',
    '    float w2=sin(ph*0.62+side*0.4)*0.20;',
    '    vec3 q=p-A;',
    '    float c=cos(w1), s=sin(w1);',
    '    q=vec3(c*q.x+s*q.z,q.y,-s*q.x+c*q.z);',
    '    n=vec3(c*n.x+s*n.z,n.y,-s*n.x+c*n.z);',
    '    c=cos(w2); s=sin(w2);',
    '    q=vec3(q.x,c*q.y-s*q.z,s*q.y+c*q.z);',
    '    n=vec3(n.x,c*n.y-s*n.z,s*n.y+c*n.z);',
    '    p=A+q;',
    '  } else if(pid>9.5&&pid<10.5){',
    '    vec3 A=vec3(0.0,0.19,0.30);',
    '    float open=(0.30+0.55*atk)*(0.5+0.5*sin(ph*3.1))*atk+0.10*(1.0-atk);',
    '    vec3 q=p-A;',
    '    float c=cos(side*open), s=sin(side*open);',
    '    q=vec3(c*q.x-s*q.z,q.y,s*q.x+c*q.z);',
    '    n=vec3(c*n.x-s*n.z,n.y,s*n.x+c*n.z);',
    '    p=A+q;',
    '  } else if(pid>2.5&&pid<3.0){',
    '    //  CREATURE LIMBS.',
    '    //',
    '    //  The leg branch above rotates about LEG_ATTACH, which is a table of',
    '    //  an ANT hip table. Run a woodlouse or a spider through it and',
    '    //  the limbs tear off, so every creature limb was parked on 2.75 - a',
    '    //  value that matches no branch at all. It kept the dark limb material',
    '    //  and lost every trace of movement: five animals walking around the',
    '    //  tank with their legs welded in place.',
    '    //',
    '    //  These have no hip table, and there are six of them with different',
    '    //  builds, so this swings the limb about the body axis instead. How',
    '    //  far a vertex is from that axis decides how much it travels, which',
    '    //  keeps the joint at the body still and lets the foot move; where the',
    '    //  limb sits around the body sets its phase, so the legs alternate the',
    '    //  way a real gait does rather than paddling in unison.',
    '    float r=length(p.xz);',
    '    float ang=atan(p.z,p.x);',
    '    float lph=ph*2.0+ang*1.7;',
    '    float reach=clamp(r*2.2,0.0,1.0);',
    '    float sw=sin(lph)*0.26*amp*reach;',
    '    float lift=max(0.0,sin(lph+1.5708))*0.055*amp*reach;',
    '    float c=cos(sw), s=sin(sw);',
    '    p=vec3(c*p.x+s*p.z, p.y+lift, -s*p.x+c*p.z);',
    '    n=vec3(c*n.x+s*n.z, n.y, -s*n.x+c*n.z);',
    '  } else if(pid<0.5){',
    '    p.y+=sin(ph*2.0)*0.004*amp;',
    '  } else if(pid>1.5&&pid<2.5){',
    '    p.y+=sin(ph*2.0+0.7)*0.008*amp;',
    '    p.z-=abs(sin(ph))*0.006*amp;',
    '  } else if(pid>11.5&&pid<12.5){',
    '    float flap=sin(extra*42.0+part.w*0.7)*0.55*step(0.01,extra);',
    '    vec3 A=vec3(side*0.03,0.255,0.02);',
    '    vec3 q=p-A;',
    '    float c=cos(side*flap), s=sin(side*flap);',
    '    q=vec3(c*q.x-s*q.y,s*q.x+c*q.y,q.z);',
    '    n=vec3(c*n.x-s*n.y,s*n.x+c*n.y,n.z);',
    '    p=A+q;',
    '  }',
    '}'
  ].join('\n');

  S.INST_ATTRIBS = [
    'in vec3 aPos;',
    'in vec3 aNrm;',
    'in vec2 aUV;',
    'in vec4 aPart;',
    'in vec4 aIPos;   // xyz pos, w scale',
    'in vec4 aIRot;   // yaw,pitch,roll, animPhase',
    'in vec4 aIAnim;  // walkAmp, attack, extra, variant',
    'in vec4 aIColA;  // base colour rgb, roughness',
    'in vec4 aIData;  // health, selected, glow, flags'
  ].join('\n');

  S.INST_TRANSFORM = [
    'mat3 eulerM(float yaw,float pitch,float roll){',
    '  float cy=cos(yaw),sy=sin(yaw),cp=cos(pitch),sp=sin(pitch),cr=cos(roll),sr=sin(roll);',
    '  mat3 Ry=mat3(cy,0.0,-sy, 0.0,1.0,0.0, sy,0.0,cy);',
    '  mat3 Rx=mat3(1.0,0.0,0.0, 0.0,cp,sp, 0.0,-sp,cp);',
    '  mat3 Rz=mat3(cr,sr,0.0, -sr,cr,0.0, 0.0,0.0,1.0);',
    '  return Ry*Rx*Rz;',
    '}'
  ].join('\n');

  S.CREATURE_VS = [
    S.HEAD,
    S.INST_ATTRIBS,
    S.INST_TRANSFORM,
    S.ANT_ANIM,
    'uniform mat4 uVP;',
    'uniform float uTime;',
    'uniform float uIsAnt;',
    'out vec3 vWorld;',
    'out vec3 vNormal;',
    'out vec2 vUV;',
    'out vec4 vPart;',
    'out vec4 vColA;',
    'out vec4 vData;',
    'out vec3 vLocal;',
    'void main(){',
    '  //  BROOD STAGE SELECTOR.',
    '  //',
    '  //  buildBrood packs an egg, a larva and a pupa into ONE mesh and tags',
    '  //  each with aPart.w = 0/1/2; the instance carries its own stage in',
    '  //  aIAnim.w. The comment in geometry.js has always said the shader',
    '  //  picks between them - but nothing ever did, so every brood item drew',
    '  //  all three shapes stacked on top of each other and a nursery was a',
    '  //  row of identical white beans whatever was actually growing in it.',
    '  //',
    '  //  Collapsing the losing vertices to a point outside the clip volume',
    '  //  costs one compare and needs no extra varying. uIsAnt is 0 only for',
    '  //  brood, so ants and the bestiary are untouched.',
    '  if(uIsAnt<0.5 && abs(aPart.w-aIAnim.w)>0.5){',
    '    gl_Position=vec4(2.0,2.0,2.0,1.0);',
    '    vWorld=vec3(0.0); vNormal=vec3(0.0,1.0,0.0); vUV=vec2(0.0);',
    '    vPart=aPart; vColA=aIColA; vData=aIData; vLocal=vec3(0.0);',
    '    return;',
    '  }',
    '  vec3 p=aPos; vec3 n=aNrm;',
    '  vec4 anim=vec4(aIRot.w,aIAnim.x,aIAnim.y,aIAnim.z);',
    '  animPart(p,n,aPart,anim);',
    '  vLocal=p;',
    '  mat3 R=eulerM(aIRot.x,aIRot.y,aIRot.z);',
    '  vec3 wp=R*(p*aIPos.w)+aIPos.xyz;',
    '  vWorld=wp;',
    '  vNormal=normalize(R*n);',
    '  vUV=aUV; vPart=aPart; vColA=aIColA; vData=aIData;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');

  S.CREATURE_FS = [
    S.HEAD,
    S.NOISE,
    S.LIGHTING,
    S.SHADOW,
    'in vec3 vWorld;',
    'in vec3 vNormal;',
    'in vec2 vUV;',
    'in vec4 vPart;',
    'in vec4 vColA;',
    'in vec4 vData;',
    'in vec3 vLocal;',
    'uniform float uTime;',
    'uniform float uIsAnt;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    'void main(){',
    '  vec3 N=normalize(vNormal);',
    '  vec3 V=normalize(uCamPos-vWorld);',
    '  vec3 albedo=vColA.rgb;',
    '  float rough=vColA.a;',
    '  float metal=0.0;',
    '  float spec=1.0;',
    '  float pid=vPart.x;',
    '  float health=vData.x;',
    '  float glow=vData.z;',
    '  float flags=vData.w;',
    '  float limb=0.0;',
    '  // --- chitin detail ---',
    '  if(uIsAnt>0.5){',
    '    float seg=fbm(vLocal*46.0,2);',
    '    albedo*=0.86+0.30*seg;',
    '    // punctures / micro pits',
    '    float pit=smoothstep(0.42,0.30,worley(vLocal*90.0));',
    '    albedo*=1.0-pit*0.35;',
    '    rough=clamp(rough+pit*0.25-0.08*seg,0.06,1.0);',
    '    if(pid>0.5&&pid<1.5&&vPart.w>0.5){ albedo=vec3(0.02,0.018,0.022); rough=0.09; spec=2.2; }',
    '    //  Legs, antennae and mandibles are darker and matte on a real ant.',
    '    //  Left at body colour and body gloss they are thin enough that the',
    '    //  fresnel rim covers the whole limb and they read as white paper.',
    '    if(pid>2.5&&pid<10.5){',
    '      //  Absolute, not a multiplier: a thin limb catches so much ambient',
    '      //  and rim light that scaling the body colour still came out pale.',
    '      albedo=mix(vec3(0.070,0.040,0.026),albedo*0.30,0.35);',
    '      rough=0.88; spec=0.06;',
    '      limb=1.0;',
    '    }',
    '    if(pid>1.5&&pid<2.5){',
    '      float band=sin(vLocal.z*46.0)*0.5+0.5;',
    '      albedo*=0.80+0.34*band;',
    '      rough*=0.82;',
    '    }',
    '    //  TAGMA CONTRAST (real ants only - uIsAnt 2, not the bestiary at 1).',
    '    //',
    '    //  The three body sections were one flat orange, so at any distance the',
    '    //  ant read as a single mass and the waist it actually has was invisible.',
    '    //  Ants are not one colour: the mesosoma is the lightest and warmest part,',
    '    //  the head is darker and cooler, and the gaster is darkest of all. Giving',
    '    //  each tagma its own value is what makes the three-part body legible even',
    '    //  when the ant is thirty pixels across.',
    '    //',
    '    //  Multiplicative on the instance colour, so every caste and every colony',
    '    //  tint keeps its own hue and only the RELATIVE values change.',
    '    if(uIsAnt>1.5){',
    '      if(pid<0.5){ albedo*=vec3(1.20,1.10,0.98); }',
    '      else if(pid<1.5){ albedo*=vec3(0.66,0.60,0.60); }',
    '      else if(pid>1.5&&pid<2.5){ albedo*=vec3(0.62,0.55,0.54); }',
    '      else if(pid>10.5&&pid<11.5){ albedo*=vec3(0.70,0.64,0.62); }',
    '    }',
    '    if(pid>11.5&&pid<12.5){ albedo=vec3(0.72,0.76,0.82); rough=0.07; spec=1.6; }',
    '    // damage darkening',
    '    albedo*=mix(0.42,1.0,clamp(health,0.0,1.0));',
    '  }',
    '  // fungal infection: chalky green bloom + sprouting',
    '  float infect=step(0.5,mod(flags,2.0));',
    '  if(infect>0.5){',
    '    float f=fbm(vWorld*9.0+uTime*0.05,3);',
    '    albedo=mix(albedo,vec3(0.42,0.55,0.24),smoothstep(0.42,0.72,f)*0.85);',
    '    rough=mix(rough,0.95,0.7);',
    '  }',
    '  float NoL=max(dot(N,uSunDir),0.0);',
    '  float sh=shadowAt(vWorld,NoL);',
    '  vec3 col=shadeDirect(N,V,uSunDir,uSunCol,albedo,rough,metal,spec)*sh;',
    '  col+=ambientIBL(N,V,albedo,rough,metal,1.0);',
    '  col+=pointLights(vWorld,N,V,albedo,rough,metal,spec);',
    '  // chitin sheen: fresnel rim with slight iridescence',
    '  float fres=pow(1.0-max(dot(N,V),0.0),4.0);',
    '  vec3 irid=0.5+0.5*cos(vec3(0.0,2.1,4.2)+fres*7.0+vLocal.z*3.0);',
    '  col+=fres*mix(vec3(1.0),irid,0.55)*0.16*uIsAnt*(1.0-limb);',
    '  //  Brood colouring. With the selector above doing its job, vPart.w is',
    '  //  this instance stage. Eggs are small and pearly, larvae are fatter and',
    '  //  creamier, pupae darken and go tan as they mature - which is what lets',
    '  //  a player read the state of a nursery at a glance instead of counting',
    '  //  identical beans.',
    '  if(uIsAnt<0.5){',
    '    float st=vPart.w;',
    '    if(st<0.5){ col*=vec3(1.06,1.05,1.02); }',
    '    else if(st<1.5){ col*=vec3(1.00,0.95,0.80); }',
    '    else { col*=vec3(0.80,0.66,0.46); }',
    '  }',
    '  // selection + faction glow',
    '  col+=vColA.rgb*glow;',
    '  float sel=vData.y;',
    '  if(sel>0.01){',
    '    float rim=pow(1.0-max(dot(N,V),0.0),2.0);',
    '    col+=vec3(0.35,0.95,1.25)*rim*sel*1.6;',
    '  }',
    '  oColor=vec4(col,1.0);',
    '  oNormal=vec4(N*0.5+0.5,rough);',
    '}'
  ].join('\n');

  // depth-only variant for shadow map
  S.SHADOW_VS = [
    S.HEAD,
    S.INST_ATTRIBS,
    S.INST_TRANSFORM,
    S.ANT_ANIM,
    'uniform mat4 uVP;',
    'void main(){',
    '  vec3 p=aPos; vec3 n=aNrm;',
    '  vec4 anim=vec4(aIRot.w,aIAnim.x,aIAnim.y,aIAnim.z);',
    '  animPart(p,n,aPart,anim);',
    '  mat3 R=eulerM(aIRot.x,aIRot.y,aIRot.z);',
    '  vec3 wp=R*(p*aIPos.w)+aIPos.xyz;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');
  S.SHADOW_FS = [
    S.HEAD,
    'out vec4 oC;',
    'void main(){ oC=vec4(1.0); }'
  ].join('\n');

  // ==================================================================
  //  4. STATIC WORLD MESHES  (frames, shelf, room)
  // ==================================================================
  S.STATIC_VS = [
    S.HEAD,
    'in vec3 aPos; in vec3 aNrm; in vec2 aUV; in vec4 aPart;',
    'uniform mat4 uVP; uniform mat4 uModel;',
    'out vec3 vWorld; out vec3 vNormal; out vec2 vUV; out vec4 vPart;',
    'void main(){',
    '  vec4 wp=uModel*vec4(aPos,1.0);',
    '  vWorld=wp.xyz;',
    '  vNormal=mat3(uModel)*aNrm;',
    '  vUV=aUV; vPart=aPart;',
    '  gl_Position=uVP*wp;',
    '}'
  ].join('\n');

  S.STATIC_FS = [
    S.HEAD,
    S.NOISE,
    S.LIGHTING,
    S.SHADOW,
    'in vec3 vWorld; in vec3 vNormal; in vec2 vUV; in vec4 vPart;',
    'uniform vec3 uAlbedo;',
    'uniform float uRough;',
    'uniform float uMetal;',
    'uniform float uMatType;  // 0 generic, 1 wood, 2 metal, 3 plaster',
    'uniform float uTime;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    'void main(){',
    '  vec3 N=normalize(vNormal);',
    '  vec3 V=normalize(uCamPos-vWorld);',
    '  vec3 albedo=uAlbedo; float rough=uRough; float metal=uMetal;',
    '  if(uMatType<1.5&&uMatType>0.5){',
    '    float grain=fbm(vec3(vWorld.x*2.0,vWorld.y*38.0,vWorld.z*2.0),4);',
    '    float rings=sin(vWorld.y*8.0+grain*7.0)*0.5+0.5;',
    '    albedo*=0.68+0.5*grain+0.16*rings;',
    '    rough=clamp(rough+0.18*(0.5-grain),0.2,1.0);',
    '  } else if(uMatType>1.5&&uMatType<2.5){',
    '    float brush=fbm(vWorld*vec3(60.0,4.0,60.0),3);',
    '    rough=clamp(rough+brush*0.18-0.09,0.05,1.0);',
    '  } else if(uMatType>2.5){',
    '    float n=fbm(vWorld*4.0,4);',
    '    albedo*=0.9+0.2*n;',
    '  }',
    '  float NoL=max(dot(N,uSunDir),0.0);',
    '  float sh=shadowAt(vWorld,NoL);',
    '  vec3 col=shadeDirect(N,V,uSunDir,uSunCol,albedo,rough,metal,1.0)*sh;',
    '  col+=ambientIBL(N,V,albedo,rough,metal,1.0);',
    '  col+=pointLights(vWorld,N,V,albedo,rough,metal,1.0);',
    '  oColor=vec4(col,1.0);',
    '  oNormal=vec4(N*0.5+0.5,rough);',
    '}'
  ].join('\n');

  // ==================================================================
  //  5. VEGETATION (instanced, wind-animated)
  // ==================================================================
  S.FLORA_VS = [
    S.HEAD,
    S.INST_ATTRIBS,
    S.INST_TRANSFORM,
    'uniform mat4 uVP;',
    'uniform float uTime;',
    'out vec3 vWorld; out vec3 vNormal; out vec2 vUV; out vec4 vPart; out vec4 vColA; out vec4 vData;',
    'out float vSeed; out float vSway;',
    'void main(){',
    '  vec3 p=aPos;',
    '  float t=aPart.y;',
    '  float ph=aIPos.x*0.7+aIPos.z*0.53+aIAnim.w*6.2;',
    '  // two-octave breeze plus a faster flutter so blades never move in lockstep',
    '  float sway=sin(uTime*1.15+ph)*0.105',
    '            +sin(uTime*2.65+ph*1.7)*0.048',
    '            +sin(uTime*5.30+ph*3.1)*0.016;',
    '  float stiff=t*t*(1.0+aIAnim.w*0.5);',
    '  p.x+=sway*stiff*1.7;',
    '  p.z+=sway*stiff*0.85;',
    '  p.y-=sway*sway*stiff*0.9;   // arc, not a shear',
    '  mat3 R=eulerM(aIRot.x,aIRot.y,aIRot.z);',
    '  vec3 wp=R*(p*aIPos.w)+aIPos.xyz;',
    '  vWorld=wp;',
    '  vNormal=normalize(R*aNrm);',
    '  vUV=aUV; vPart=aPart; vColA=aIColA; vData=aIData;',
    '  vSeed=aIAnim.w; vSway=sway;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');

  S.FLORA_FS = [
    S.HEAD,
    S.NOISE,
    S.LIGHTING,
    S.SHADOW,
    'in vec3 vWorld; in vec3 vNormal; in vec2 vUV; in vec4 vPart; in vec4 vColA; in vec4 vData;',
    'in float vSeed; in float vSway;',
    'uniform float uTime;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    'void main(){',
    '  vec3 N=normalize(vNormal);',
    '  if(!gl_FrontFacing) N=-N;',
    '  vec3 V=normalize(uCamPos-vWorld);',
    '  float t=clamp(vPart.y,0.0,1.0);',
    '  float kind=vPart.w;',
    '  float u=vUV.x;',
    '  float mid=abs(u-0.5)*2.0;      // 0 at the spine, 1 at the edge',
    '  vec3 base=vColA.rgb;',
    '  vec3 albedo; float rough=vColA.a; float spec=1.0; float trans=0.0;',
    '',
    '  if(kind<0.5){',
    '    // ---------------- GRASS BLADE ----------------',
    '    // sheath is pale and dry, the body is saturated, the tip is sun-bleached',
    '    vec3 sheath=base*vec3(1.05,0.86,0.52)*0.80;',
    '    vec3 body  =base;',
    '    vec3 tip   =base*vec3(1.42,1.34,0.66)+vec3(0.028,0.034,0.0);',
    '    albedo=mix(sheath,body,smoothstep(0.02,0.34,t));',
    '    albedo=mix(albedo,tip,smoothstep(0.46,1.0,t)*0.92);',
    '    // parallel veins running the length of the blade',
    '    float vein=sin(u*10.5+vSeed*3.1)*0.5+0.5;',
    '    albedo*=0.925+0.145*vein;',
    '    // the fold catches light on the wings and stays dark in the crease',
    '    albedo*=0.80+0.34*smoothstep(0.0,0.42,mid);',
    '    // sun-scorched patches, different on every blade',
    '    float dry=fbm(vec3(vWorld.xz*2.6,t*3.0+vSeed*11.0),3);',
    '    albedo=mix(albedo,albedo*vec3(1.55,1.20,0.46),smoothstep(0.58,0.86,dry)*0.55*t);',
    '    // occasional rust fleck',
    '    float rust=smoothstep(0.90,0.97,fbm(vec3(vWorld*9.0+vSeed*20.0),2));',
    '    albedo=mix(albedo,vec3(0.34,0.19,0.07),rust*0.5);',
    '    rough=mix(0.30,0.52,t);',
    '    spec=1.5;',
    '    trans=0.55+0.35*t;',
    '  } else if(kind<1.5){',
    '    // ---------------- LEAF ----------------',
    '    albedo=base*(0.86+0.30*(1.0-mid));',
    '    float rib=smoothstep(0.085,0.0,mid);',
    '    albedo=mix(albedo,base*vec3(1.55,1.48,1.05),rib*0.62);',
    '    // lateral veins sweeping out from the midrib toward the tip',
    '    float lat=sin(vUV.y*17.0-mid*6.5+vSeed*2.0);',
    '    albedo*=1.0+0.115*smoothstep(0.80,1.0,abs(lat))*(1.0-rib);',
    '    // dry necrotic margin',
    '    albedo=mix(albedo,vec3(0.26,0.165,0.072),smoothstep(0.74,1.0,mid)*0.60);',
    '    // autumn blotching',
    '    float chl=fbm(vec3(vWorld*4.2+vSeed*17.0),3);',
    '    albedo=mix(albedo,albedo*vec3(1.62,1.10,0.34),smoothstep(0.55,0.88,chl)*0.55);',
    '    albedo*=0.80+0.34*t;',
    '    rough=0.38; spec=1.35; trans=0.85;',
    '  } else if(kind<2.5){',
    '    // ---------------- MUSHROOM CAP / STEM ----------------',
    '    albedo=base;',
    '    float radial=sin(vUV.x*6.2831853*11.0)*0.5+0.5;',
    '    albedo*=0.90+0.16*radial;',
    '    float speck=smoothstep(0.80,0.90,fbm(vec3(vWorld*13.0+vSeed*7.0),2));',
    '    albedo=mix(albedo,vec3(0.94,0.92,0.86),speck*0.55);',
    '    albedo*=mix(0.62,1.10,t);   // stem darker at the base',
    '    rough=0.62; spec=0.8; trans=0.45;',
    '  } else {',
    '    // ---------------- GILLS ----------------',
    '    float radial=sin(atan(vUV.y-0.5,vUV.x-0.5)*46.0)*0.5+0.5;',
    '    albedo=base*mix(0.30,0.85,radial)*vec3(1.05,0.95,0.90);',
    '    rough=0.85; spec=0.4; trans=0.25;',
    '  }',
    '',
    '  float NoL=max(dot(N,uSunDir),0.0);',
    '  float sh=shadowAt(vWorld,NoL);',
    '  vec3 col=shadeDirect(N,V,uSunDir,uSunCol,albedo,rough,0.0,spec)*sh;',
    '  // subsurface: thin foliage lights up when the sun is behind it',
    '  float back=max(dot(-N,uSunDir),0.0);',
    '  float wrap=pow(max(dot(V,-uSunDir),0.0),2.2);',
    '  vec3 sss=albedo*vec3(1.10,1.22,0.72);',
    '  col+=sss*uSunCol*(back*0.28+wrap*0.42)*sh*trans;',
    '  col+=ambientIBL(N,V,albedo,rough,0.0,1.0);',
    '  col+=pointLights(vWorld,N,V,albedo,rough,0.0,spec);',
    '  // waxy cuticle highlight that slides as the blade moves',
    '  float fres=pow(1.0-max(dot(N,V),0.0),3.5);',
    '  col+=uSunCol*fres*0.10*sh*(1.0-mid*0.5);',
    '  col+=vColA.rgb*vData.z;',
    '  oColor=vec4(col,1.0);',
    '  oNormal=vec4(N*0.5+0.5,rough);',
    '}'
  ].join('\n');

  // ==================================================================
  //  6. GLASS  (refractive, drawn last against a copy of the scene)
  // ==================================================================
  S.GLASS_VS = [
    S.HEAD,
    'in vec3 aPos; in vec3 aNrm; in vec2 aUV; in vec4 aPart;',
    'uniform mat4 uVP; uniform mat4 uModel;',
    'out vec3 vWorld; out vec3 vNormal; out vec2 vUV;',
    'void main(){',
    '  vec4 wp=uModel*vec4(aPos,1.0);',
    '  vWorld=wp.xyz; vNormal=mat3(uModel)*aNrm; vUV=aUV;',
    '  gl_Position=uVP*wp;',
    '}'
  ].join('\n');

  S.GLASS_FS = [
    S.HEAD,
    S.NOISE,
    S.LIGHTING,
    'in vec3 vWorld; in vec3 vNormal; in vec2 vUV;',
    'uniform sampler2D uScene;',
    'uniform vec2 uRes;',
    'uniform float uTime;',
    'uniform float uTint;',
    'uniform vec3 uGlassCol;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    'void main(){',
    '  vec3 N=normalize(vNormal);',
    '  if(!gl_FrontFacing) N=-N;',
    '  vec3 V=normalize(uCamPos-vWorld);',
    '  float fres=pow(1.0-clamp(dot(N,V),0.0,1.0),5.0);',
    '  fres=0.045+0.955*fres;',
    '  //  Clean pane. The old version layered a directional streak and a',
    '  //  22x-frequency dust field over a large flat surface, which aliased and',
    '  //  crawled as the camera moved - it read as a rendering fault, not glass.',
    '  //  One very low-frequency smudge is all that survives, and only to break',
    '  //  up the refraction very slightly.',
    '  float smudge=fbm(vec3(vWorld.xy*0.55,vWorld.z*0.55),2);',
    '  vec2 uv=gl_FragCoord.xy/uRes;',
    '  vec2 off=(N.xy*0.008+vec2(smudge-0.5)*0.0015);',
    '  vec3 refr=texture(uScene,clamp(uv+off,vec2(0.001),vec2(0.999))).rgb;',
    '  // absorption: glass is faintly coloured and eats a little light',
    '  vec3 absorb=mix(vec3(1.0),uGlassCol,uTint*0.55)*0.965;',
    '  // reflections: a cheap studio environment',
    '  vec3 R=reflect(-V,N);',
    '  float up=R.y*0.5+0.5;',
    '  vec3 env=mix(uGndCol*0.5,uSkyCol*0.95,up);',
    '  float spot=pow(max(dot(R,normalize(uSunDir)),0.0),260.0);',
    '  env+=uSunCol*spot*9.0;',
    '  float spot2=pow(max(dot(R,normalize(vec3(-0.4,0.75,0.5))),0.0),120.0);',
    '  env+=vec3(0.7,0.8,1.0)*spot2*2.0;',
    '  float a=0.92;',
    '  vec3 col=refr*absorb*a;',
    '  col+=env*fres*0.55;',
    '  oColor=vec4(col,a);',   // premultiplied
    '  oNormal=vec4(N*0.5+0.5,0.05);',
    '}'
  ].join('\n');

  // ==================================================================
  //  7. PHEROMONE FIELD  (additive volumetric-ish ribbons)
  // ==================================================================
  S.PHERO_VS = [
    S.HEAD,
    'in vec3 aPos; in vec3 aNrm; in vec2 aUV; in vec4 aPart;',
    'in vec4 aIPos;  // xyz, radius',
    'in vec4 aIColA; // rgb, strength',
    'in vec4 aIData; // age, type, seed, pulse',
    'uniform mat4 uVP; uniform vec3 uRight; uniform vec3 uUp;',
    'out vec2 vUV; out vec4 vCol; out vec4 vData; out vec3 vWorld;',
    'void main(){',
    '  vec3 wp=aIPos.xyz+(uRight*aPos.x+uUp*aPos.y)*aIPos.w;',
    '  vUV=aUV; vCol=aIColA; vData=aIData; vWorld=wp;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');

  S.PHERO_FS = [
    S.HEAD,
    S.NOISE,
    'in vec2 vUV; in vec4 vCol; in vec4 vData; in vec3 vWorld;',
    'uniform float uTime;',
    'out vec4 oColor;',
    // Occlusion comes from the depth test, not a depth-texture read: the
    // scene depth buffer is still bound as the render target here.
    'void main(){',
    '  vec2 c=vUV*2.0-1.0;',
    '  float r=length(c);',
    '  if(r>1.0) discard;',
    '  float fall=pow(1.0-r,2.6);',
    '  float n=fbm(vec3(vWorld*3.0+vec3(0.0,uTime*0.35,0.0)),3);',
    '  float pulse=0.65+0.35*sin(uTime*3.4+vData.w*6.28);',
    '  float a=fall*vCol.a*pulse*(0.55+0.75*n);',
    '  if(a<0.004) discard;',
    '  oColor=vec4(vCol.rgb*a*1.5,a);',
    '}'
  ].join('\n');

  // ==================================================================
  //  8. PARTICLES
  // ==================================================================
  S.PART_VS = [
    S.HEAD,
    'in vec3 aPos; in vec2 aUV;',
    'in vec4 aIPos;   // xyz, size',
    'in vec4 aIColA;  // rgb, alpha',
    'in vec4 aIData;  // life01, kind, spin, seed',
    'uniform mat4 uVP; uniform vec3 uRight; uniform vec3 uUp;',
    'out vec2 vUV; out vec4 vCol; out vec4 vData;',
    'void main(){',
    '  float s=sin(aIData.z), c=cos(aIData.z);',
    '  vec2 q=vec2(aPos.x*c-aPos.y*s, aPos.x*s+aPos.y*c);',
    '  vec3 wp=aIPos.xyz+(uRight*q.x+uUp*q.y)*aIPos.w;',
    '  vUV=aUV; vCol=aIColA; vData=aIData;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');

  S.PART_FS = [
    S.HEAD,
    S.NOISE,
    'in vec2 vUV; in vec4 vCol; in vec4 vData;',
    'uniform float uTime;',
    'out vec4 oColor;',
    'void main(){',
    '  vec2 c=vUV*2.0-1.0;',
    '  float r=length(c);',
    '  float kind=vData.y;',
    '  float a=0.0;',
    '  if(kind<0.5){            // soft dust mote',
    '    a=smoothstep(1.0,0.0,r);',
    '    a*=a;',
    '  } else if(kind<1.5){     // spark / acid',
    '    a=smoothstep(1.0,0.15,r)*smoothstep(1.0,0.55,abs(c.y)*0.4+r*0.6);',
    '    a=pow(a,1.6);',
    '  } else if(kind<2.5){     // dirt clod',
    '    float n=hash12(floor(c*4.0)+vData.w*13.0);',
    '    a=step(r,0.85+n*0.15);',
    '  } else if(kind<3.5){     // smoke / spore puff',
    '    float n=fbm(vec3(c*2.4,vData.w*7.0+uTime*0.15),3);',
    '    a=smoothstep(1.0,0.1,r+n*0.5-0.25);',
    '  } else {                 // glow ring',
    '    a=smoothstep(0.05,0.0,abs(r-0.75))*1.4;',
    '  }',
    '  a*=vCol.a;',
    '  if(a<0.004) discard;',
    '  oColor=vec4(vCol.rgb*a,a);',
    '}'
  ].join('\n');

  // ==================================================================
  //  9. GROUND DECALS  (selection rings, order markers, zone rings)
  // ==================================================================
  S.DECAL_VS = [
    S.HEAD,
    'in vec3 aPos; in vec2 aUV;',
    'in vec4 aIPos;  // xyz, radius',
    'in vec4 aIColA; // rgb, alpha',
    'in vec4 aIData; // style, phase, thickness, seed',
    'uniform mat4 uVP;',
    'out vec2 vUV; out vec4 vCol; out vec4 vData;',
    'void main(){',
    '  //  aIData.w: 0 lies flat on the ground, 1 stands upright in the',
    '  //  cross-section plane. A chamber preview has to be vertical - the nest',
    '  //  is a slab against the glass, not a floor plan.',
    '  vec3 off = (aIData.w > 0.5)',
    '    ? vec3(aPos.x, aPos.y, 0.0)',
    '    : vec3(aPos.x, 0.0, aPos.y);',
    '  vec3 wp=aIPos.xyz+off*aIPos.w;',
    '  vUV=aPos.xy; vCol=aIColA; vData=aIData;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');

  S.DECAL_FS = [
    S.HEAD,
    'in vec2 vUV; in vec4 vCol; in vec4 vData;',
    'uniform float uTime;',
    'out vec4 oColor;',
    'void main(){',
    '  float r=length(vUV);',
    '  float a=0.0;',
    '  float style=vData.x;',
    '  float th=vData.z;',
    '  if(style<0.5){',
    '    a=smoothstep(th,0.0,abs(r-0.86));',
    '    float ticks=step(0.62,abs(sin(atan(vUV.y,vUV.x)*8.0+vData.y)));',
    '    a*=0.35+0.65*ticks;',
    '  } else if(style<1.5){',
    '    float rr=fract(vData.y);',
    '    a=smoothstep(th,0.0,abs(r-rr))*(1.0-rr);',
    '  } else {',
    '    a=smoothstep(1.0,0.25,r)*0.55;',
    '    a+=smoothstep(th,0.0,abs(r-0.94))*0.9;',
    '  }',
    '  a*=vCol.a;',
    '  if(a<0.004) discard;',
    '  oColor=vec4(vCol.rgb*a,a);',
    '}'
  ].join('\n');

  // ==================================================================
  //  10. ROOM / BACKDROP
  // ==================================================================
  S.SKY_FS = [
    S.HEAD,
    S.NOISE,
    'in vec2 vUV;',
    'uniform mat4 uInvVP;',
    'uniform vec3 uCamPos;',
    'uniform vec3 uSunDir;',
    'uniform vec3 uSunCol;',
    'uniform float uTime;',
    'uniform vec3 uRoomA;',
    'uniform vec3 uRoomB;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    'void main(){',
    '  vec4 h=uInvVP*vec4(vUV*2.0-1.0,1.0,1.0);',
    '  vec3 rd=normalize(h.xyz/h.w-uCamPos);',
    '  float up=rd.y*0.5+0.5;',
    '  vec3 col=mix(uRoomA,uRoomB,pow(up,0.8));',
    '  // distant lab window glow behind the shelf',
    '  float win=pow(max(dot(rd,normalize(uSunDir)),0.0),9.0);',
    '  col+=uSunCol*win*0.55;',
    '  // vertical wall gradient + faint texture',
    '  float n=fbm(rd*7.0,4);',
    '  col*=0.92+0.16*n;',
    '  // dust in the air',
    '  float m=smoothstep(0.986,1.0,hash12(floor(rd.xy*260.0)+floor(uTime*0.6)));',
    '  col+=vec3(0.5,0.55,0.6)*m*0.35;',
    '  oColor=vec4(col,1.0);',
    '  oNormal=vec4(0.5,0.5,1.0,1.0);',
    '}'
  ].join('\n');

  // ==================================================================
  //  11. LIQUIDS (honey / water pools, sugar syrup)
  // ==================================================================
  S.LIQUID_VS = [
    S.HEAD,
    S.INST_ATTRIBS,
    S.INST_TRANSFORM,
    'uniform mat4 uVP; uniform float uTime;',
    'out vec3 vWorld; out vec3 vNormal; out vec2 vUV; out vec4 vColA; out vec4 vData;',
    'void main(){',
    '  vec3 p=aPos;',
    '  float w=sin(uTime*2.1+p.x*5.0+aIPos.x)*0.012+sin(uTime*3.3+p.z*6.0)*0.008;',
    '  p.y+=w*aPart.y;',
    '  mat3 R=eulerM(aIRot.x,aIRot.y,aIRot.z);',
    '  vec3 wp=R*(p*aIPos.w)+aIPos.xyz;',
    '  vWorld=wp; vNormal=normalize(R*aNrm); vUV=aUV; vColA=aIColA; vData=aIData;',
    '  gl_Position=uVP*vec4(wp,1.0);',
    '}'
  ].join('\n');

  S.LIQUID_FS = [
    S.HEAD,
    S.NOISE,
    S.LIGHTING,
    'in vec3 vWorld; in vec3 vNormal; in vec2 vUV; in vec4 vColA; in vec4 vData;',
    'uniform sampler2D uScene; uniform vec2 uRes; uniform float uTime;',
    'layout(location=0) out vec4 oColor;',
    'layout(location=1) out vec4 oNormal;',
    'void main(){',
    '  vec3 N=normalize(vNormal);',
    '  vec3 V=normalize(uCamPos-vWorld);',
    '  //  Two crossing ripple trains at different speeds. One fbm layer just',
    '  //  wobbles; two moving against each other read as a live surface.',
    '  float rA=fbm(vec3(vWorld.xz*7.0, uTime*0.55),3);',
    '  float rB=fbm(vec3(vWorld.zx*11.0+31.0,-uTime*0.37),2);',
    '  vec2 wob=vec2(rA-0.5,rB-0.5);',
    '  N=normalize(N+vec3(wob.x,0.0,wob.y)*0.42);',
    '  //  INTERIOR FLATTENING. vData.x is the neighbour count, normalised.',
    '  //  A blob buried inside the body of the pool has many neighbours, so',
    '  //  we bend its normal towards straight up; every interior blob then',
    '  //  shares one normal, the Sobel in the post chain finds no crease',
    '  //  between them, and the ink outline is drawn ONCE around the whole',
    '  //  puddle silhouette instead of around every single bead. That is',
    '  //  what turns a bag of marbles into a body of water in an ink game.',
    '  N=normalize(mix(N,vec3(0.0,1.0,0.0),smoothstep(0.20,0.70,vData.x)));',
    '  float fres=pow(1.0-clamp(dot(N,V),0.0,1.0),4.0);',
    '  fres=0.03+0.97*fres;',
    '  //  Depth tint: the middle of a pool is deeper, so it holds more colour',
    '  //  than the feathered rim. vPart.y runs 0 at the centre to 1 at the edge.',
    '  //  How deep is this blob sitting in the pool? The old code derived it',
    '  //  from the mesh UV, which meant every particle was tinted as if it',
    '  //  were the whole puddle. vData.y carries real submergence in world',
    '  //  units from the solver, so a shallow film reads pale and a filled',
    '  //  pit reads deep.',
    '  float deep=clamp(vData.y/1.6,0.0,1.0);',
    '  vec2 uv=gl_FragCoord.xy/uRes+N.xz*(0.020+0.030*deep);',
    '  vec3 behind=texture(uScene,clamp(uv,vec2(0.002),vec2(0.998))).rgb;',
    '  //  Beer-Lambert-ish: the further light travels through the water the',
    '  //  more of the warm end it loses, which is what makes water look wet',
    '  //  rather than like blue glass laid on the sand.',
    '  vec3 absorb=exp(-vec3(1.65,0.55,0.26)*deep*1.9);',
    '  vec3 col=behind*mix(vec3(1.0),vColA.rgb*1.7,0.55)*absorb;',
    '  vec3 R=reflect(-V,N);',
    '  col+=mix(uGndCol,uSkyCol,R.y*0.5+0.5)*fres*0.85;',
    '  col+=uSunCol*pow(max(dot(R,uSunDir),0.0),220.0)*16.0;',
    '  // a second, softer glint so the surface sparkles as it moves',
    '  col+=uSunCol*pow(max(dot(R,uSunDir),0.0),34.0)*0.16;',
    '  col+=pointLights(vWorld,N,V,vColA.rgb,0.04,0.0,2.4);',
    '  float la=clamp(0.30+deep*0.45+fres*0.42,0.0,1.0);',
    '  oColor=vec4(col*la,la);',
    '  oNormal=vec4(N*0.5+0.5,0.04);',
    '}'
  ].join('\n');

  //  Damp soil under a pool. Drawn with the MULTIPLY blend, which is the
  //  only way to darken what is already in the buffer - an additive pass
  //  cannot, and trying it is what previously turned a "dark ring" into
  //  bright arcs around every puddle.
  S.WET_FS = [
    S.HEAD,
    'in vec2 vUV; in vec4 vCol; in vec4 vData;',
    'uniform float uTime;',
    'out vec4 oColor;',
    'void main(){',
    '  float r=length(vUV);',
    '  float a=smoothstep(1.0,0.35,r)*vCol.a;',
    '  if(a<0.004) discard;',
    '  //  darken and desaturate slightly - wet sand, not grey paint',
    '  oColor=vec4(mix(vec3(1.0),vec3(0.55,0.48,0.42),a),a);',
    '}'
  ].join('\n');

  AF.S = S;
})(window.AF = window.AF || {});
