/* =============================================================
   FORMICARIUM :: DEEP COLONY
   shaders_post.js - post-processing chain
   SSAO -> Bloom -> DOF -> God rays -> Tonemap/Grade -> FXAA
   ============================================================= */
(function (AF) {
  'use strict';
  var S = AF.S;
  var P = {};

  var H = S.HEAD;

  // ---------------------------------------------------------------
  //  SSAO
  // ---------------------------------------------------------------
  P.SSAO_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uDepth;',
    'uniform sampler2D uNormal;',
    'uniform mat4 uInvProj;',
    'uniform mat4 uProj;',
    'uniform mat4 uView;',
    'uniform vec2 uRes;',
    'uniform float uRadius;',
    'uniform float uStrength;',
    'uniform float uTime;',
    'out vec4 oCol;',
    'vec3 viewFromDepth(vec2 uv,float d){',
    '  vec4 c=uInvProj*vec4(uv*2.0-1.0,d*2.0-1.0,1.0);',
    '  return c.xyz/c.w;',
    '}',
    'float hash12(vec2 p){ vec3 p3=fract(vec3(p.xyx)*0.1031); p3+=dot(p3,p3.yzx+33.33); return fract((p3.x+p3.y)*p3.z); }',
    'void main(){',
    '  float d=texture(uDepth,vUV).r;',
    '  if(d>=0.99999){ oCol=vec4(1.0); return; }',
    '  vec3 P0=viewFromDepth(vUV,d);',
    '  vec3 Nw=texture(uNormal,vUV).xyz*2.0-1.0;',
    '  vec3 N=normalize(mat3(uView)*Nw);',
    '  float ang=hash12(vUV*uRes+uTime*0.0)*6.2831853;',
    '  float ca=cos(ang), sa=sin(ang);',
    '  float occ=0.0;',
    '  const int NS=16;',
    '  float r=uRadius;',
    '  for(int i=0;i<NS;i++){',
    '    float fi=float(i);',
    '    float a=fi*2.39996323;',
    '    float rad=sqrt((fi+0.5)/float(NS));',
    '    vec2 dir=vec2(cos(a),sin(a));',
    '    dir=vec2(dir.x*ca-dir.y*sa,dir.x*sa+dir.y*ca);',
    '    vec3 sdir=vec3(dir*rad,0.0);',
    '    // hemisphere orient',
    '    vec3 t=normalize(abs(N.z)<0.9?cross(N,vec3(0,0,1)):cross(N,vec3(1,0,0)));',
    '    vec3 b=cross(N,t);',
    '    vec3 sp=P0+(t*sdir.x+b*sdir.y+N*(0.25+0.75*rad))*r;',
    '    vec4 cp=uProj*vec4(sp,1.0);',
    '    vec2 suv=(cp.xy/cp.w)*0.5+0.5;',
    '    if(suv.x<0.0||suv.x>1.0||suv.y<0.0||suv.y>1.0) continue;',
    '    float sd=texture(uDepth,suv).r;',
    '    vec3 sampleP=viewFromDepth(suv,sd);',
    '    float dz=sampleP.z-sp.z;',
    '    float rangeCheck=smoothstep(0.0,1.0,r/max(abs(P0.z-sampleP.z),1e-4));',
    '    occ+=(dz>0.02?1.0:0.0)*rangeCheck;',
    '  }',
    '  occ=1.0-occ/float(NS)*uStrength;',
    '  oCol=vec4(clamp(occ,0.0,1.0),0.0,0.0,1.0);',
    '}'
  ].join('\n');

  P.BLUR_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform sampler2D uDepth;',
    'uniform vec2 uDir;',
    'uniform vec2 uTexel;',
    'out vec4 oCol;',
    'void main(){',
    '  float c=texture(uTex,vUV).r;',
    '  float dc=texture(uDepth,vUV).r;',
    '  float sum=c, wsum=1.0;',
    '  for(int i=1;i<=4;i++){',
    '    float fi=float(i);',
    '    float w=exp(-fi*fi*0.16);',
    '    vec2 o=uDir*uTexel*fi*1.35;',
    '    float d1=texture(uDepth,vUV+o).r, d2=texture(uDepth,vUV-o).r;',
    '    float w1=w*exp(-abs(d1-dc)*900.0);',
    '    float w2=w*exp(-abs(d2-dc)*900.0);',
    '    sum+=texture(uTex,vUV+o).r*w1+texture(uTex,vUV-o).r*w2;',
    '    wsum+=w1+w2;',
    '  }',
    '  oCol=vec4(sum/wsum,0.0,0.0,1.0);',
    '}'
  ].join('\n');

  // ---------------------------------------------------------------
  //  BLOOM
  // ---------------------------------------------------------------
  P.BRIGHT_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform float uThreshold;',
    'uniform float uSoft;',
    'out vec4 oCol;',
    'void main(){',
    '  vec3 c=texture(uTex,vUV).rgb;',
    '  float br=max(c.r,max(c.g,c.b));',
    '  float knee=uThreshold*uSoft+1e-5;',
    '  float soft=clamp(br-uThreshold+knee,0.0,2.0*knee);',
    '  soft=soft*soft/(4.0*knee);',
    '  float w=max(soft,br-uThreshold)/max(br,1e-5);',
    '  oCol=vec4(c*w,1.0);',
    '}'
  ].join('\n');

  P.DOWN_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform vec2 uTexel;',
    'out vec4 oCol;',
    'void main(){',
    '  vec2 t=uTexel;',
    '  vec3 a=texture(uTex,vUV+vec2(-t.x,-t.y)).rgb;',
    '  vec3 b=texture(uTex,vUV+vec2( t.x,-t.y)).rgb;',
    '  vec3 c=texture(uTex,vUV+vec2(-t.x, t.y)).rgb;',
    '  vec3 d=texture(uTex,vUV+vec2( t.x, t.y)).rgb;',
    '  vec3 e=texture(uTex,vUV).rgb;',
    '  vec3 f=texture(uTex,vUV+vec2(-2.0*t.x,0.0)).rgb;',
    '  vec3 g=texture(uTex,vUV+vec2( 2.0*t.x,0.0)).rgb;',
    '  vec3 h=texture(uTex,vUV+vec2(0.0,-2.0*t.y)).rgb;',
    '  vec3 i=texture(uTex,vUV+vec2(0.0, 2.0*t.y)).rgb;',
    '  oCol=vec4((a+b+c+d)*0.125+e*0.25+(f+g+h+i)*0.0625+e*0.125,1.0);',
    '}'
  ].join('\n');

  P.UP_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform sampler2D uPrev;',
    'uniform vec2 uTexel;',
    'uniform float uScatter;',
    'out vec4 oCol;',
    'void main(){',
    '  vec2 t=uTexel*uScatter;',
    '  vec3 s=texture(uTex,vUV+vec2(-t.x,-t.y)).rgb*0.0625;',
    '  s+=texture(uTex,vUV+vec2(0.0,-t.y)).rgb*0.125;',
    '  s+=texture(uTex,vUV+vec2(t.x,-t.y)).rgb*0.0625;',
    '  s+=texture(uTex,vUV+vec2(-t.x,0.0)).rgb*0.125;',
    '  s+=texture(uTex,vUV).rgb*0.25;',
    '  s+=texture(uTex,vUV+vec2(t.x,0.0)).rgb*0.125;',
    '  s+=texture(uTex,vUV+vec2(-t.x,t.y)).rgb*0.0625;',
    '  s+=texture(uTex,vUV+vec2(0.0,t.y)).rgb*0.125;',
    '  s+=texture(uTex,vUV+vec2(t.x,t.y)).rgb*0.0625;',
    '  oCol=vec4(texture(uPrev,vUV).rgb+s,1.0);',
    '}'
  ].join('\n');

  // ---------------------------------------------------------------
  //  DEPTH OF FIELD (macro-lens look)
  // ---------------------------------------------------------------
  P.COC_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uColor;',
    'uniform sampler2D uDepth;',
    'uniform float uNear; uniform float uFar;',
    'uniform float uFocus; uniform float uAperture; uniform float uMaxCoC;',
    'out vec4 oCol;',
    'float linz(float d){ float z=d*2.0-1.0; return (2.0*uNear*uFar)/(uFar+uNear-z*(uFar-uNear)); }',
    'void main(){',
    '  float z=linz(texture(uDepth,vUV).r);',
    '  float coc=(z-uFocus)/max(z,0.001)*uAperture;',
    '  coc=clamp(coc,-uMaxCoC,uMaxCoC);',
    '  oCol=vec4(texture(uColor,vUV).rgb,coc);',
    '}'
  ].join('\n');

  P.DOF_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform vec2 uTexel;',
    'uniform float uMaxCoC;',
    'out vec4 oCol;',
    'void main(){',
    '  vec4 c0=texture(uTex,vUV);',
    '  float coc=c0.a;',
    '  float r=abs(coc);',
    '  if(r<0.6){ oCol=c0; return; }',
    '  vec3 sum=c0.rgb; float wsum=1.0;',
    '  const int N=22;',
    '  for(int i=0;i<N;i++){',
    '    float fi=float(i);',
    '    float a=fi*2.39996323;',
    '    float rad=sqrt((fi+0.5)/float(N))*r;',
    '    vec2 o=vec2(cos(a),sin(a))*rad*uTexel;',
    '    vec4 s=texture(uTex,vUV+o);',
    '    float w=clamp(abs(s.a)/max(r,1e-3),0.15,1.0);',
    '    // bokeh: weight bright pixels more for highlight blooming',
    '    float b=1.0+dot(s.rgb,vec3(0.2126,0.7152,0.0722))*0.35;',
    '    sum+=s.rgb*w*b; wsum+=w*b;',
    '  }',
    '  oCol=vec4(sum/wsum,coc);',
    '}'
  ].join('\n');

  // ---------------------------------------------------------------
  //  GOD RAYS
  // ---------------------------------------------------------------
  P.GODRAY_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform vec2 uSunUV;',
    'uniform float uDecay; uniform float uDensity; uniform float uWeight; uniform float uExposure;',
    'out vec4 oCol;',
    'void main(){',
    '  vec2 uv=vUV;',
    '  vec2 delta=(uv-uSunUV)*(uDensity/48.0);',
    '  float illum=1.0;',
    '  vec3 acc=vec3(0.0);',
    '  for(int i=0;i<48;i++){',
    '    uv-=delta;',
    '    vec3 s=texture(uTex,clamp(uv,vec2(0.0),vec2(1.0))).rgb;',
    '    acc+=s*illum*uWeight;',
    '    illum*=uDecay;',
    '  }',
    '  oCol=vec4(acc*uExposure,1.0);',
    '}'
  ].join('\n');

  // ---------------------------------------------------------------
  //  FINAL COMPOSITE
  // ---------------------------------------------------------------
  P.COMPOSITE_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uColor;',
    'uniform sampler2D uBloom;',
    'uniform sampler2D uAO;',
    'uniform sampler2D uDOF;',
    'uniform sampler2D uRays;',
    'uniform sampler2D uDepth;',
    'uniform vec2 uRes;',
    'uniform float uTime;',
    'uniform float uBloomAmt;',
    'uniform float uAOAmt;',
    'uniform float uExposure;',
    'uniform float uVignette;',
    'uniform float uGrain;',
    'uniform float uCA;',
    'uniform float uSat;',
    'uniform float uContrast;',
    'uniform vec3 uLift;',
    'uniform vec3 uGain;',
    'uniform float uRaysAmt;',
    'uniform float uDofAmt;',
    'uniform float uFlash;',
    'uniform vec3 uFlashCol;',
    'uniform sampler2D uNormalTex;',
    'uniform float uOutline;',
    'uniform float uPaper;',
    'uniform float uNear;',
    'uniform float uFar;',
    'out vec4 oCol;',
    'float linz(float d){ float z=d*2.0-1.0; return (2.0*uNear*uFar)/(uFar+uNear-z*(uFar-uNear)); }',
    '//  Storybook ink line: a Sobel-ish sniff of the depth and normal buffers.',
    '//  Depth catches silhouettes, normals catch creases the depth misses.',
    'float inkEdge(vec2 uv, vec2 px){',
    '  float d0=texture(uDepth,uv).r;',
    '  if(d0>=0.99999) return 0.0;',
    '  vec3 n0=texture(uNormalTex,uv).xyz*2.0-1.0;',
    '  float e=0.0;',
    '  for(int i=0;i<4;i++){',
    '    vec2 o=(i==0)?vec2(px.x,0.0):(i==1)?vec2(-px.x,0.0):(i==2)?vec2(0.0,px.y):vec2(0.0,-px.y);',
    '    float d=texture(uDepth,uv+o).r;',
    '    vec3 n=texture(uNormalTex,uv+o).xyz*2.0-1.0;',
    '    e+=abs(d-d0)/max(1.0-d0,1e-4)*0.9;',
    '    e+=(1.0-max(dot(n,n0),0.0))*0.55;',
    '  }',
    '  return clamp(e,0.0,1.0);',
    '}',
    'float hash12(vec2 p){ vec3 p3=fract(vec3(p.xyx)*0.1031); p3+=dot(p3,p3.yzx+33.33); return fract((p3.x+p3.y)*p3.z); }',
    'vec3 ACESFitted(vec3 x){',
    '  const mat3 mIn=mat3(0.59719,0.07600,0.02840, 0.35458,0.90834,0.13383, 0.04823,0.01566,0.83777);',
    '  const mat3 mOut=mat3(1.60475,-0.10208,-0.00327, -0.53108,1.10813,-0.07276, -0.07367,-0.00605,1.07602);',
    '  vec3 v=mIn*x;',
    '  vec3 a=v*(v+0.0245786)-0.000090537;',
    '  vec3 b=v*(0.983729*v+0.4329510)+0.238081;',
    '  return clamp(mOut*(a/b),0.0,1.0);',
    '}',
    'void main(){',
    '  vec2 uv=vUV;',
    '  vec2 c=uv-0.5;',
    '  float r2=dot(c,c);',
    '  // chromatic aberration grows toward the edge (macro-lens feel)',
    '  vec2 caO=c*r2*uCA;',
    '  vec3 sharp;',
    '  sharp.r=texture(uColor,uv+caO).r;',
    '  sharp.g=texture(uColor,uv).g;',
    '  sharp.b=texture(uColor,uv-caO).b;',
    '  vec4 dof=texture(uDOF,uv);',
    '  float blend=clamp(abs(dof.a)*0.55,0.0,1.0)*uDofAmt;',
    '  vec3 col=mix(sharp,dof.rgb,blend);',
    '  float ao=texture(uAO,uv).r;',
    '  ao=mix(1.0,ao,uAOAmt);',
    '  col*=ao;',
    '  col+=texture(uBloom,uv).rgb*uBloomAmt;',
    '  col+=texture(uRays,uv).rgb*uRaysAmt;',
    '  col+=uFlashCol*uFlash;',
    '  //  ink the edges before tonemapping so the line sits in the art, not on top',
    '  if(uOutline>0.001){',
    '    float e=inkEdge(uv,1.0/uRes);',
    '    e=smoothstep(0.22,0.72,e)*uOutline;',
    '    //  Thin the line with distance. At full strength on everything, a',
    '    //  blade of grass forty units away is a two-pixel shape wearing a',
    '    //  one-pixel black outline - the whole surface turns into cut-out',
    '    //  stickers. Near things keep their full line.',
    '    float zc=linz(texture(uDepth,uv).r);',
    '    e*=clamp(1.25-(zc-5.0)*0.030,0.22,1.0);',
    '    col=mix(col,col*vec3(0.13,0.11,0.10),e);',
    '  }',
    '  col*=uExposure;',
    '  col=ACESFitted(col);',
    '  // grade',
    '  col=pow(max(col,vec3(0.0)),vec3(1.0/2.2));',
    '  float l=dot(col,vec3(0.2126,0.7152,0.0722));',
    '  col=mix(vec3(l),col,uSat);',
    '  col=(col-0.5)*uContrast+0.5;',
    '  col=col*uGain+uLift;',
    '  // vignette',
    '  float vig=1.0-uVignette*smoothstep(0.20,0.95,r2*2.1);',
    '  col*=vig;',
    '  // paper tooth: a faint static speckle that reads as printed stock',
    '  if(uPaper>0.001){',
    '    float pg=hash12(floor(uv*uRes*0.5))*2.0-1.0;',
    '    col*=1.0+pg*uPaper;',
    '  }',
    '  // film grain',
    '  float g=hash12(uv*uRes+fract(uTime)*137.0)-0.5;',
    '  col+=g*uGrain*(1.0-l*0.6);',
    '  oCol=vec4(clamp(col,0.0,1.0),1.0);',
    '}'
  ].join('\n');

  // ---------------------------------------------------------------
  //  FXAA + light sharpen, straight to the screen
  // ---------------------------------------------------------------
  P.FXAA_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'uniform vec2 uTexel;',
    'uniform float uSharp;',
    'out vec4 oCol;',
    'float lum(vec3 c){ return dot(c,vec3(0.299,0.587,0.114)); }',
    'void main(){',
    '  vec3 rgbM=texture(uTex,vUV).rgb;',
    '  vec3 rgbNW=texture(uTex,vUV+vec2(-1.0,-1.0)*uTexel).rgb;',
    '  vec3 rgbNE=texture(uTex,vUV+vec2( 1.0,-1.0)*uTexel).rgb;',
    '  vec3 rgbSW=texture(uTex,vUV+vec2(-1.0, 1.0)*uTexel).rgb;',
    '  vec3 rgbSE=texture(uTex,vUV+vec2( 1.0, 1.0)*uTexel).rgb;',
    '  float lNW=lum(rgbNW),lNE=lum(rgbNE),lSW=lum(rgbSW),lSE=lum(rgbSE),lM=lum(rgbM);',
    '  float lMin=min(lM,min(min(lNW,lNE),min(lSW,lSE)));',
    '  float lMax=max(lM,max(max(lNW,lNE),max(lSW,lSE)));',
    '  vec2 dir=vec2(-((lNW+lNE)-(lSW+lSE)),((lNW+lSW)-(lNE+lSE)));',
    '  float dirReduce=max((lNW+lNE+lSW+lSE)*0.25*0.125,0.0078125);',
    '  float rcpDir=1.0/(min(abs(dir.x),abs(dir.y))+dirReduce);',
    '  dir=clamp(dir*rcpDir,vec2(-8.0),vec2(8.0))*uTexel;',
    '  vec3 rgbA=0.5*(texture(uTex,vUV+dir*(1.0/3.0-0.5)).rgb+texture(uTex,vUV+dir*(2.0/3.0-0.5)).rgb);',
    '  vec3 rgbB=rgbA*0.5+0.25*(texture(uTex,vUV+dir*-0.5).rgb+texture(uTex,vUV+dir*0.5).rgb);',
    '  float lB=lum(rgbB);',
    '  vec3 res=(lB<lMin||lB>lMax)?rgbA:rgbB;',
    '  // contrast-adaptive sharpen',
    '  vec3 blur=(rgbNW+rgbNE+rgbSW+rgbSE)*0.25;',
    '  res+=(res-blur)*uSharp;',
    '  oCol=vec4(clamp(res,0.0,1.0),1.0);',
    '}'
  ].join('\n');

  // simple copy
  P.COPY_FS = [
    H,
    'in vec2 vUV;',
    'uniform sampler2D uTex;',
    'out vec4 oCol;',
    'void main(){ oCol=texture(uTex,vUV); }'
  ].join('\n');

  AF.SP = P;
})(window.AF = window.AF || {});
